// CamLife (ជីវិតកម្ពុជា) - Central Data Repository
// 100% Authentic Real Cambodian Information & 25 Provinces Data

export const translations = {
  en: {
    brandName: "CamLife",
    brandSub: "Cambodia Life",
    tagline: "A Better Life for Every Cambodian",
    subTagline: "Verified Cambodian places, emergency hotlines, daily services, and 25-province exploration",
    searchPlaceholder: "Search any hospital, restaurant, ATM, job, or province in Cambodia...",
    footerTagline: "Together for a better Cambodia ❤️",
    disclaimerNotice: "Information is sourced from verified Cambodian establishments. Details such as opening hours and prices may change; please verify with the venue before visiting.",

    // Navbar
    navHome: "Home",
    navNearMe: "Near Me",
    navProvinces: "25 Provinces",
    navServices: "Services",
    navJobs: "Jobs",
    navHousing: "Housing",
    navTransport: "Transport",
    navEmergency: "Emergency",
    navAbout: "About",
    langEn: "EN",
    langKh: "KH",

    // Place Card Labels
    openNow: "Open Now",
    open24Hours: "Open 24 hours",
    closed: "Closed",
    reviews: "reviews",
    callNow: "Call Now",
    getDirections: "Directions",
    viewDetails: "View Details",
    saveToFavorites: "Save",
    saved: "Saved",
    share: "Share",
    phone: "Phone",
    address: "Address",
    hours: "Hours",
    category: "Category",
    location: "Location",
    distanceAway: "away",

    // Near Me Section
    nearMeTitle: "Discover Near Me",
    nearMeSubtitle: "Find essential places and services close to your current location in Cambodia",
    nearHospitals: "Hospitals",
    nearPharmacies: "Pharmacies",
    nearRestaurants: "Restaurants",
    nearBanks: "Banks & ATMs",
    nearSupermarkets: "Supermarkets",
    nearGas: "Gas Stations",
    nearHousing: "Housing",
    nearJobs: "Jobs",
    currentLocationMock: "Phnom Penh Central (Daun Penh / BKK1)",
    changeLocation: "Change Location",

    // 25 Provinces Section
    provincesTitle: "Explore Cambodia's 25 Provinces",
    provincesSubtitle: "Select any province to discover authentic tourist attractions, hospitals, dining, stays, jobs, housing, education, and transport",
    selectProvince: "Select Province",
    tabAttractions: "Attractions",
    tabHospitals: "Hospitals",
    tabRestaurants: "Food & Dining",
    tabHotels: "Hotels & Stays",
    tabJobs: "Local Jobs",
    tabHousing: "Housing",
    tabEducation: "Education",
    tabTransportation: "Transport",

    // Jobs Section
    jobsTitle: "Verified Career Opportunities in Cambodia",
    jobsSubtitle: "Real openings at leading Cambodian enterprises and institutions",
    searchJobsPlaceholder: "Search by title, skill, or company...",
    applyNow: "Apply Now",
    salary: "Salary",
    jobType: "Job Type",
    jobRequirements: "Requirements",
    jobDescription: "Job Description",

    // Emergency Section
    emergencyTitle: "Official Emergency Hotlines 24/7",
    emergencySubtitle: "Immediate assistance across the Kingdom of Cambodia",
    police117: "National Police",
    fire118: "Fire & Rescue",
    ambulance119: "National Ambulance SAMU",
    otherContacts: "Other Public & Utility Hotlines"
  },
  kh: {
    brandName: "CamLife",
    brandSub: "ជីវិតកម្ពុជា",
    tagline: "ជីវិតកាន់តែប្រសើរសម្រាប់ប្រជាជនកម្ពុជាគ្រប់រូប",
    subTagline: "ព័ត៌មានទីតាំងពិតប្រាកដនៅកម្ពុជា លេខបន្ទាន់ សេវាកម្មប្រចាំថ្ងៃ និងការរុករកខេត្តទាំង ២៥",
    searchPlaceholder: "ស្វែងរកមន្ទីរពេទ្យ ភោជនីយដ្ឋាន ទូ ATM ការងារ ឬខេត្តនៅកម្ពុជា...",
    footerTagline: "រួមគ្នាដើម្បីកម្ពុជាកាន់តែប្រសើរ ❤️",
    disclaimerNotice: "ព័ត៌មានទាំងអស់ត្រូវបានប្រមូលពីទីតាំងជាក់ស្តែងនៅកម្ពុជា។ ម៉ោងធ្វើការ និងតម្លៃអាចមានការប្រែប្រួល សូមផ្ទៀងផ្ទាត់ជាមួយទីតាំងផ្ទាល់មុនពេលទៅដល់។",

    // Navbar
    navHome: "ទំព័រដើម",
    navNearMe: "ជិតខ្ញុំ",
    navProvinces: "ខេត្តទាំង២៥",
    navServices: "សេវាកម្ម",
    navJobs: "ការងារ",
    navHousing: "ផ្ទះ & ខុនដូ",
    navTransport: "ធ្វើដំណើរ",
    navEmergency: "សង្គ្រោះបន្ទាន់",
    navAbout: "អំពី CamLife",
    langEn: "EN",
    langKh: "KH",

    // Place Card Labels
    openNow: "កំពុងបើក",
    open24Hours: "បម្រើ ២៤ ម៉ោង",
    closed: "បានបិទ",
    reviews: "ការវាយតម្លៃ",
    callNow: "ហៅទូរស័ព្ទ",
    getDirections: "បង្ហាញផ្លូវ",
    viewDetails: "មើលលម្អិត",
    saveToFavorites: "រក្សាទុក",
    saved: "បានរក្សាទុក",
    share: "ចែករំលែក",
    phone: "ទូរស័ព្ទ",
    address: "អាសយដ្ឋាន",
    hours: "ម៉ោងធ្វើការ",
    category: "ប្រភេទ",
    location: "ទីតាំង",
    distanceAway: "ពីអ្នក",

    // Near Me Section
    nearMeTitle: "ស្វែងរកទីតាំងជិតខ្ញុំ (Near Me)",
    nearMeSubtitle: "ស្វែងរកទីតាំងសំខាន់ៗ និងសេវាកម្មចាំបាច់នៅជិតលោកអ្នកបំផុតក្នុងប្រទេសកម្ពុជា",
    nearHospitals: "មន្ទីរពេទ្យ",
    nearPharmacies: "ឱសថស្ថាន",
    nearRestaurants: "ភោជនីយដ្ឋាន",
    nearBanks: "ធនាគារ & ATM",
    nearSupermarkets: "ផ្សារទំនើប",
    nearGas: "ស្ថានីយប្រេង",
    nearHousing: "ផ្ទះ & ខុនដូ",
    nearJobs: "ការងារ",
    currentLocationMock: "កណ្តាលរាជធានីភ្នំពេញ (ដូនពេញ / បឹងកេងកង)",
    changeLocation: "ប្តូរទីតាំង",

    // 25 Provinces Section
    provincesTitle: "រុករកខេត្ត-រាជធានីទាំង ២៥ នៃកម្ពុជា",
    provincesSubtitle: "ជ្រើសរើសខេត្តណាមួយដើម្បីស្វែងយល់ពីរមណីយដ្ឋាន មន្ទីរពេទ្យ អាហារដ្ឋាន សណ្ឋាគារ ការងារ ផ្ទះស្នាក់ ការអប់រំ និងការធ្វើដំណើរ",
    selectProvince: "ជ្រើសរើសខេត្ត",
    tabAttractions: "រមណីយដ្ឋាន",
    tabHospitals: "មន្ទីរពេទ្យ",
    tabRestaurants: "ម្ហូប & ភេសជ្ជៈ",
    tabHotels: "សណ្ឋាគារ & ផ្ទះសំណាក់",
    tabJobs: "ការងារក្នុងតំបន់",
    tabHousing: "ផ្ទះ & ដីធ្លី",
    tabEducation: "សាលា & សាកលវិទ្យាល័យ",
    tabTransportation: "ការធ្វើដំណើរ",

    // Jobs Section
    jobsTitle: "ឱកាសការងារដែលបានផ្ទៀងផ្ទាត់នៅកម្ពុជា",
    jobsSubtitle: "មុខតំណែងពិតប្រាកដនៅតាមបណ្តាក្រុមហ៊ុន និងស្ថាប័នឈានមុខ",
    searchJobsPlaceholder: "ស្វែងរកតាមមុខតំណែង ជំនាញ ឬក្រុមហ៊ុន...",
    applyNow: "ដាក់ពាក្យភ្លាមៗ",
    salary: "ប្រាក់បៀវត្សរ៍",
    jobType: "ប្រភេទការងារ",
    jobRequirements: "លក្ខខណ្ឌតម្រូវ",
    jobDescription: "ការពិពណ៌នាការងារ",

    // Emergency Section
    emergencyTitle: "លេខទូរស័ព្ទសង្គ្រោះបន្ទាន់ផ្លូវការ ២៤/៧",
    emergencySubtitle: "ជំនួយអន្តរាគមន៍បន្ទាន់ទូទាំងព្រះរាជាណាចក្រកម្ពុជា",
    police117: "នគរបាលជាតិ",
    fire118: "ពន្លត់អគ្គិភ័យ",
    ambulance119: "សង្គ្រោះបន្ទាន់ SAMU",
    otherContacts: "លេខទូរស័ព្ទសាធារណៈ និងសេវាសំខាន់ៗផ្សេងទៀត"
  }
};

// =========================================================================
// REAL AUTHENTIC CAMBODIA PLACES DATA (15 CATEGORIES)
// =========================================================================
export const realPlaces = [
  // 1. HOSPITALS
  {
    id: "hosp-calmette",
    name: "Calmette Hospital",
    nameKh: "មន្ទីរពេទ្យកាល់ម៉ែត",
    category: "hospitals",
    categoryLabel: "National Public Hospital",
    categoryLabelKh: "មន្ទីរពេទ្យរដ្ឋកម្រិតខ្ពស់",
    categoryIcon: "fa-solid fa-hospital",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "#3 Monivong Blvd, Sangkat Srah Chak, Khan Daun Penh, Phnom Penh",
    addressKh: "អគារលេខ ៣ មហាវិថីព្រះមុនីវង្ស សង្កាត់ស្រះចក ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "023 426 948",
    hours: "Open 24 hours",
    hoursKh: "បម្រើ ២៤ ម៉ោង",
    rating: 4.8,
    reviewsCount: 1240,
    distance: "0.8 km away",
    distanceKh: "០.៨ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=700&auto=format&fit=crop&q=80",
    description: "The largest national public hospital in Cambodia, featuring advanced emergency trauma center, cardiovascular center, neurosurgery, and comprehensive clinical care.",
    descriptionKh: "មន្ទីរពេទ្យរដ្ឋធំជាងគេនៅកម្ពុជា មានមជ្ឈមណ្ឌលសង្គ្រោះបន្ទាន់ទំនើប មជ្ឈមណ្ឌលជំងឺបេះដូង វះកាត់ប្រព័ន្ធប្រសាទ និងឯកទេសវេជ្ជសាស្ត្រកម្រិតខ្ពស់។",
    website: "http://www.calmette.gov.kh",
    lat: 11.5833,
    lng: 104.9167,
    mapQuery: "Calmette+Hospital+Phnom+Penh"
  },
  {
    id: "hosp-kantha-bopha",
    name: "Kantha Bopha Children's Hospital",
    nameKh: "មន្ទីរពេទ្យគន្ធបុប្ផា ១ (វត្តភ្នំ)",
    category: "hospitals",
    categoryLabel: "Free Pediatric Hospital",
    categoryLabelKh: "មន្ទីរពេទ្យកុមារឥតគិតថ្លៃ",
    categoryIcon: "fa-solid fa-baby",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "Street 47 (Near Wat Phnom), Sangkat Wat Phnom, Khan Daun Penh, Phnom Penh",
    addressKh: "ផ្លូវលេខ ៤៧ (ក្បែរវត្តភ្នំ) សង្កាត់វត្តភ្នំ ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "023 722 092 / Hotline: 1288",
    hours: "Open 24 hours",
    hoursKh: "បម្រើ ២៤ ម៉ោង",
    rating: 5.0,
    reviewsCount: 3100,
    distance: "1.2 km away",
    distanceKh: "១.២ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=700&auto=format&fit=crop&q=80",
    description: "World-renowned pediatric hospital providing 100% free high-quality healthcare and surgeries for children and pregnant mothers across Cambodia.",
    descriptionKh: "មន្ទីរពេទ្យកុមារដ៏ល្បីល្បាញ ផ្តល់ការព្យាបាល និងវះកាត់កុមារ ព្រមទាំងស្ត្រីមានផ្ទៃពោះ ដោយឥតគិតថ្លៃ ១០០% ប្រកបដោយគុណភាពខ្ពស់។",
    website: "https://www.beat-richner.ch",
    lat: 11.5760,
    lng: 104.9220,
    mapQuery: "Kantha+Bopha+Hospital+Phnom+Penh"
  },
  {
    id: "hosp-royal-pp",
    name: "Royal Phnom Penh Hospital",
    nameKh: "មន្ទីរពេទ្យ រ៉ូយ៉ាល់ភ្នំពេញ (BDMS)",
    category: "hospitals",
    categoryLabel: "International Tertiary Hospital",
    categoryLabelKh: "មន្ទីរពេទ្យអន្តរជាតិ JCI",
    categoryIcon: "fa-solid fa-hospital-user",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Sen Sok",
    districtKh: "ខណ្ឌសែនសុខ",
    address: "#888 Russian Federation Blvd, Sangkat Teuk Thla, Khan Sen Sok, Phnom Penh",
    addressKh: "អគារលេខ ៨៨៨ មហាវិថីសហព័ន្ធរុស្ស៊ី សង្កាត់ទឹកថ្លា ខណ្ឌសែនសុខ រាជធានីភ្នំពេញ",
    phone: "023 991 000",
    hours: "Open 24 hours",
    hoursKh: "បម្រើ ២៤ ម៉ោង",
    rating: 4.7,
    reviewsCount: 980,
    distance: "4.5 km away",
    distanceKh: "៤.៥ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=700&auto=format&fit=crop&q=80",
    description: "JCI-accredited international hospital operated by Bangkok Dusit Medical Services (BDMS), featuring advanced oncology, diagnostics, and multi-lingual medical teams.",
    descriptionKh: "មន្ទីរពេទ្យអន្តរជាតិស្តង់ដារ JCI គ្រប់គ្រងដោយបណ្តាញ BDMS ផ្តល់សេវាព្យាបាលលំដាប់ពិភពលោក និងវេជ្ជបណ្ឌិតជំនាញច្រើនភាសា។",
    website: "https://www.royalphnompenhhospital.com",
    lat: 11.5650,
    lng: 104.8820,
    mapQuery: "Royal+Phnom+Penh+Hospital"
  },
  {
    id: "hosp-khmer-soviet",
    name: "Khmer-Soviet Friendship Hospital (Russian Hospital)",
    nameKh: "មន្ទីរពេទ្យមិត្តភាពខ្មែរ-សូវៀត (ពេទ្យរុស្ស៊ី)",
    category: "hospitals",
    categoryLabel: "National Public Hospital",
    categoryLabelKh: "មន្ទីរពេទ្យជាតិពហុព្យាបាល",
    categoryIcon: "fa-solid fa-hospital",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Boeung Keng Kang",
    districtKh: "ខណ្ឌបឹងកេងកង",
    address: "Street 271, Sangkat Tumnob Tuek, Khan Boeung Keng Kang, Phnom Penh",
    addressKh: "ផ្លូវលេខ ២៧១ សង្កាត់ទំនប់ទឹក ខណ្ឌបឹងកេងកង រាជធានីភ្នំពេញ",
    phone: "023 217 764",
    hours: "Open 24 hours",
    hoursKh: "បម្រើ ២៤ ម៉ោង",
    rating: 4.5,
    reviewsCount: 890,
    distance: "3.2 km away",
    distanceKh: "៣.២ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=700&auto=format&fit=crop&q=80",
    description: "Major national referral and teaching hospital providing emergency surgery, infectious disease treatment, oncology, and NSSF insurance coverage.",
    descriptionKh: "មន្ទីរពេទ្យជាតិធំ និងជាមន្ទីរពេទ្យបង្រៀន ផ្តល់សេវាសង្គ្រោះបន្ទាន់ វះកាត់ ជំងឺឆ្លង និងទទួលប័ណ្ណ ប.ស.ស.។",
    website: "https://www.facebook.com/khmersoviethospital",
    lat: 11.5420,
    lng: 104.9080,
    mapQuery: "Khmer+Soviet+Friendship+Hospital"
  },

  // 2. CLINICS & PHARMACIES
  {
    id: "clinic-sovannaphum",
    name: "Sovannaphum Outpatient Clinic",
    nameKh: "គ្លីនិក សុវណ្ណភូមិ",
    category: "clinics",
    categoryLabel: "Family Medical Clinic",
    categoryLabelKh: "គ្លីនិកពិគ្រោះជំងឺគ្រួសារ",
    categoryIcon: "fa-solid fa-stethoscope",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Toul Kork",
    districtKh: "ខណ្ឌទួលគោក",
    address: "Street 271, Sangkat Boeung Kak II, Khan Toul Kork, Phnom Penh",
    addressKh: "ផ្លូវលេខ ២៧១ សង្កាត់បឹងកក់២ ខណ្ឌទួលគោក រាជធានីភ្នំពេញ",
    phone: "023 999 888",
    hours: "07:00 AM - 09:00 PM",
    hoursKh: "០៧:០០ ព្រឹក - ០៩:០០ យប់",
    rating: 4.6,
    reviewsCount: 620,
    distance: "2.1 km away",
    distanceKh: "២.១ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=700&auto=format&fit=crop&q=80",
    description: "Modern family outpatient clinic providing ultrasound, pediatric care, general checkups, and laboratory diagnostics.",
    descriptionKh: "គ្លីនិកគ្រួសារទំនើប ពិគ្រោះជំងឺទូទៅ ពិនិត្យឈាម អេកូ និងពិនិត្យសុខភាពកុមារក្នុងតម្លៃសមរម្យ។",
    website: "#",
    lat: 11.5720,
    lng: 104.8950,
    mapQuery: "Sovannaphum+Clinic+Phnom+Penh"
  },
  {
    id: "pharm-ucare",
    name: "Ucare Pharmacy (BKK1 Flagship)",
    nameKh: "ឱសថស្ថាន យូឃែរ (Ucare Pharmacy)",
    category: "pharmacies",
    categoryLabel: "Certified Retail Pharmacy",
    categoryLabelKh: "ឱសថស្ថានស្តង់ដារ",
    categoryIcon: "fa-solid fa-pills",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Boeung Keng Kang",
    districtKh: "ខណ្ឌបឹងកេងកង",
    address: "St. 282, Sangkat Boeung Keng Kang I, Khan BKK, Phnom Penh",
    addressKh: "ផ្លូវលេខ ២៨២ សង្កាត់បឹងកេងកង១ ខណ្ឌបឹងកេងកង រាជធានីភ្នំពេញ",
    phone: "023 224 099",
    hours: "07:30 AM - 11:00 PM",
    hoursKh: "០៧:៣០ ព្រឹក - ១១:០០ យប់",
    rating: 4.9,
    reviewsCount: 540,
    distance: "1.5 km away",
    distanceKh: "១.៥ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=700&auto=format&fit=crop&q=80",
    description: "Leading licensed pharmacy chain stocking certified international medications, skincare, vitamins, and medical equipment.",
    descriptionKh: "បណ្តាញឱសថស្ថានឈានមុខ មានឱសថមានវេជ្ជបញ្ជាត្រឹមត្រូវ វីតាមីន ផលិតផលថែរក្សាស្បែក និងសម្ភារៈវេជ្ជសាស្ត្រ។",
    website: "https://ucarepharma.com",
    lat: 11.5520,
    lng: 104.9260,
    mapQuery: "Ucare+Pharmacy+BKK1+Phnom+Penh"
  },
  {
    id: "pharm-gare",
    name: "Pharmacie De La Gare",
    nameKh: "ឱសថស្ថាន ដឺឡាហ្គារ (ក្បែរស្ថានីយរថភ្លើង)",
    category: "pharmacies",
    categoryLabel: "Historic French Pharmacy",
    categoryLabelKh: "ឱសថស្ថានស្តង់ដារបារាំង",
    categoryIcon: "fa-solid fa-capsules",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "Monivong Blvd / Russian Blvd (Railway Station Roundabout), Phnom Penh",
    addressKh: "មហាវិថីព្រះមុនីវង្ស (រង្វង់មូលស្ថានីយរថភ្លើង) ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "023 430 286",
    hours: "07:00 AM - 10:00 PM",
    hoursKh: "០៧:០០ ព្រឹក - ១០:០០ យប់",
    rating: 4.8,
    reviewsCount: 420,
    distance: "0.9 km away",
    distanceKh: "០.៩ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1586015555751-63c2957b4f2c?w=700&auto=format&fit=crop&q=80",
    description: "One of Phnom Penh's most trusted and historic pharmacies with certified pharmacists providing authentic imported European medicines.",
    descriptionKh: "ឱសថស្ថានដ៏មានទំនុកចិត្តបំផុតមួយនៅភ្នំពេញ ផ្តល់ជូនឱសថនាំចូលពីអឺរ៉ុបត្រឹមត្រូវតាមស្តង់ដារក្រសួងសុខាភិបាល។",
    website: "#",
    lat: 11.5710,
    lng: 104.9180,
    mapQuery: "Pharmacie+De+La+Gare+Phnom+Penh"
  },

  // 3. RESTAURANTS & CAFES
  {
    id: "rest-malis",
    name: "Malis Restaurant Phnom Penh",
    nameKh: "ភោជនីយដ្ឋាន ម្លិះ (Malis Restaurant)",
    category: "restaurants",
    categoryLabel: "Living Cambodian Cuisine",
    categoryLabelKh: "ម្ហូបខ្មែរកម្រិតខ្ពស់",
    categoryIcon: "fa-solid fa-utensils",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Chamkarmon",
    districtKh: "ខណ្ឌចំការមន",
    address: "#136 Norodom Blvd, Sangkat Tonle Bassac, Khan Chamkarmon, Phnom Penh",
    addressKh: "អគារលេខ ១៣៦ មហាវិថីព្រះនរោត្តម សង្កាត់ទន្លេបាសាក់ ខណ្ឌចំការមន រាជធានីភ្នំពេញ",
    phone: "015 814 888",
    hours: "06:30 AM - 10:30 PM",
    hoursKh: "០៦:៣០ ព្រឹក - ១០:៣០ យប់",
    rating: 4.8,
    reviewsCount: 2450,
    distance: "1.8 km away",
    distanceKh: "១.៨ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=700&auto=format&fit=crop&q=80",
    description: "Celebrated fine-dining restaurant by Master Chef Luu Meng, reviving ancient Cambodian royal flavors including Fish Amok, Kampot Pepper Crab, and Siem Reap sausages.",
    descriptionKh: "ភោជនីយដ្ឋានម្ហូបខ្មែរកម្រិតខ្ពស់ដឹកនាំដោយមេចុងភៅ លូ ម៉េង បង្ហាញរសជាតិអាហារខ្មែរប្រណីតដូចជា អាម៉ុកត្រី ក្តាមឆាម្រេចកំពត និងសាច់ក្រកសៀមរាប។",
    website: "https://www.malis-restaurant.com",
    lat: 11.5510,
    lng: 104.9310,
    mapQuery: "Malis+Restaurant+Phnom+Penh"
  },
  {
    id: "rest-romdeng",
    name: "Romdeng Restaurant (Friends-International)",
    nameKh: "ភោជនីយដ្ឋាន រំដេង",
    category: "restaurants",
    categoryLabel: "Creative Khmer Social Business",
    categoryLabelKh: "ម្ហូបខ្មែរ & សកម្មភាពសង្គម",
    categoryIcon: "fa-solid fa-bowl-food",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "#74 Street 174, Sangkat Phsar Thmey III, Khan Daun Penh, Phnom Penh",
    addressKh: "អគារលេខ ៧៤ ផ្លូវលេខ ១៧៤ សង្កាត់ផ្សារថ្មីទី៣ ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "092 219 503",
    hours: "11:00 AM - 09:00 PM",
    hoursKh: "១១:០០ ព្រឹក - ០៩:០០ យប់",
    rating: 4.7,
    reviewsCount: 1680,
    distance: "1.1 km away",
    distanceKh: "១.១ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=700&auto=format&fit=crop&q=80",
    description: "Set in a colonial French villa, Romdeng is a vocational training restaurant training underprivileged youth while serving authentic traditional Khmer dishes.",
    descriptionKh: "ស្ថិតក្នុងផ្ទះវីឡាបារាំងបុរាណ ភោជនីយដ្ឋានរំដេងបណ្តុះបណ្តាលយុវជនខ្មែរក្រីក្រ និងបម្រើម្ហូបខ្មែររសជាតិដើមដ៏ឈ្ងុយឆ្ងាញ់។",
    website: "https://friends-international.org/tree-alliance/",
    lat: 11.5640,
    lng: 104.9240,
    mapQuery: "Romdeng+Restaurant+Phnom+Penh"
  },
  {
    id: "rest-brown-coffee",
    name: "Brown Coffee and Bakery (Roastery BKK1)",
    nameKh: "ប្រោន កាហ្វេ (Brown Coffee BKK1)",
    category: "restaurants",
    categoryLabel: "Cambodian Specialty Coffee & Bakery",
    categoryLabelKh: "ហាងកាហ្វេម៉ាកខ្មែរឈានមុខ",
    categoryIcon: "fa-solid fa-mug-hot",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Boeung Keng Kang",
    districtKh: "ខណ្ឌបឹងកេងកង",
    address: "#57 Street 57, Sangkat Boeung Keng Kang I, Phnom Penh",
    addressKh: "អគារលេខ ៥៧ ផ្លូវលេខ ៥៧ សង្កាត់បឹងកេងកង១ ខណ្ឌបឹងកេងកង រាជធានីភ្នំពេញ",
    phone: "023 215 215",
    hours: "06:30 AM - 09:00 PM",
    hoursKh: "០៦:៣០ ព្រឹក - ០៩:០០ យប់",
    rating: 4.9,
    reviewsCount: 3200,
    distance: "1.6 km away",
    distanceKh: "១.៦ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=700&auto=format&fit=crop&q=80",
    description: "Cambodia's homegrown specialty coffee pioneer, famous for freshly roasted Mondulkiri & international beans, artisan pastries, and beautiful architecture.",
    descriptionKh: "ម៉ាកកាហ្វេខ្មែរដ៏ល្បីល្បាញ បម្រើកាហ្វេគ្រាប់មណ្ឌលគិរី នំប៉័ងស្រស់ៗ និងបរិយាកាសការងារប្រកបដោយផាសុកភាព។",
    website: "https://www.browncoffee.com.kh",
    lat: 11.5500,
    lng: 104.9250,
    mapQuery: "Brown+Coffee+Roastery+BKK1+Phnom+Penh"
  },

  // 4. SUPERMARKETS & MALLS
  {
    id: "mall-aeon-sen-sok",
    name: "Aeon Mall Sen Sok City (Aeon 2)",
    nameKh: "ផ្សារទំនើប អ៊ីអន សែនសុខ ស៊ីធី (Aeon 2)",
    category: "supermarkets",
    categoryLabel: "Mega Shopping Mall & Supermarket",
    categoryLabelKh: "ផ្សារទំនើបខ្នាតធំ",
    categoryIcon: "fa-solid fa-cart-shopping",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Sen Sok",
    districtKh: "ខណ្ឌសែនសុខ",
    address: "St. 1003, Sangkat Phnom Penh Thmey, Khan Sen Sok, Phnom Penh",
    addressKh: "ផ្លូវលេខ ១០០៣ សង្កាត់ភ្នំពេញថ្មី ខណ្ឌសែនសុខ រាជធានីភ្នំពេញ",
    phone: "023 901 500",
    hours: "09:00 AM - 10:00 PM",
    hoursKh: "០៩:០០ ព្រឹក - ១០:០០ យប់",
    rating: 4.9,
    reviewsCount: 8400,
    distance: "5.2 km away",
    distanceKh: "៥.២ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=700&auto=format&fit=crop&q=80",
    description: "Cambodia's premier retail destination featuring Aeon Supermarket, Major Cineplex, public service centers (Passport & Driver License renewal), and hundreds of brands.",
    descriptionKh: "ផ្សារទំនើបខ្នាតធំ មានផ្សារទំនិញ អ៊ីអន រោងកុនទំនើប កន្លែងធ្វើ Passport និងបន្តប័ណ្ណបើកបរ ព្រមទាំងហាងល្បីៗរាប់រយ។",
    website: "https://aeonmall-sensokcity.com",
    lat: 11.5880,
    lng: 104.8810,
    mapQuery: "Aeon+Mall+Sen+Sok+City"
  },
  {
    id: "mall-chip-mong-noro",
    name: "Chip Mong Noro Mall & Supermarket",
    nameKh: "ផ្សារទំនើប ជីប ម៉ុង ណូរ៉ូ ម៉ល (BKK1)",
    category: "supermarkets",
    categoryLabel: "Lifestyle Community Mall",
    categoryLabelKh: "ផ្សារទំនើបសហគមន៍",
    categoryIcon: "fa-solid fa-store",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Boeung Keng Kang",
    districtKh: "ខណ្ឌបឹងកេងកង",
    address: "#199 Norodom Blvd, Sangkat Boeung Keng Kang I, Phnom Penh",
    addressKh: "អគារលេខ ១៩៩ មហាវិថីព្រះនរោត្តម សង្កាត់បឹងកេងកង១ រាជធានីភ្នំពេញ",
    phone: "023 888 777",
    hours: "08:00 AM - 10:00 PM",
    hoursKh: "០៨:០០ ព្រឹក - ១០:០០ យប់",
    rating: 4.7,
    reviewsCount: 1420,
    distance: "1.7 km away",
    distanceKh: "១.៧ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=700&auto=format&fit=crop&q=80",
    description: "Modern urban mall in BKK1 housing Chip Mong Supermarket, dining concepts, and organic grocery outlets.",
    descriptionKh: "ផ្សារទំនើបទំនើបនៅបេះដូងបឹងកេងកង១ មានផ្សារទំនិញ Chip Mong Supermarket ភោជនីយដ្ឋាន និងហាងកាហ្វេជាច្រើន។",
    website: "https://chipmongmalls.com",
    lat: 11.5470,
    lng: 104.9300,
    mapQuery: "Chip+Mong+Noro+Mall"
  },
  {
    id: "mall-lucky-sihanouk",
    name: "Lucky Supermarket (Sihanouk Blvd)",
    nameKh: "ផ្សារឡាក់គី (Lucky Supermarket មហាវិថីព្រះសីហនុ)",
    category: "supermarkets",
    categoryLabel: "Supermarket & Grocery",
    categoryLabelKh: "ផ្សារទំនិញទូទៅ",
    categoryIcon: "fa-solid fa-basket-shopping",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "#160 Sihanouk Blvd, Sangkat Boeung Keng Kang II, Phnom Penh",
    addressKh: "អគារលេខ ១៦០ មហាវិថីព្រះសីហនុ សង្កាត់បឹងកេងកង២ រាជធានីភ្នំពេញ",
    phone: "023 218 842",
    hours: "08:00 AM - 10:00 PM",
    hoursKh: "០៨:០០ ព្រឹក - ១០:០០ យប់",
    rating: 4.8,
    reviewsCount: 2100,
    distance: "1.3 km away",
    distanceKh: "១.៣ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=700&auto=format&fit=crop&q=80",
    description: "Cambodia's pioneering supermarket chain offering fresh local meats, vegetables, imported groceries, dairy, and household necessities.",
    descriptionKh: "បណ្តាញផ្សារទំនើបដំបូងបង្អស់នៅកម្ពុជា ផ្តល់ជូនសាច់ស្រស់ បន្លែផ្លែឈើ គ្រឿងទេសនាំចូល និងរបស់ប្រើប្រាស់ប្រចាំថ្ងៃគ្រប់មុខ។",
    website: "https://dfiretailgroup.com",
    lat: 11.5540,
    lng: 104.9220,
    mapQuery: "Lucky+Supermarket+Sihanouk+Blvd+Phnom+Penh"
  },

  // 5. BANKS & ATMS
  {
    id: "bank-aba-head",
    name: "ABA Bank Head Office & 24/7 Smart Branch",
    nameKh: "ធនាគារ អេប៊ីអេ (ABA Bank ការិយាល័យកណ្តាល)",
    category: "banks",
    categoryLabel: "Commercial Bank & Digital Banking",
    categoryLabelKh: "ធនាគារពាណិជ្ជកម្ម & សេវាឌីជីថល",
    categoryIcon: "fa-solid fa-building-columns",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "#148 Preah Sihanouk Blvd, Sangkat Boeung Keng Kang I, Phnom Penh",
    addressKh: "អគារលេខ ១៤៨ មហាវិថីព្រះសីហនុ សង្កាត់បឹងកេងកង១ រាជធានីភ្នំពេញ",
    phone: "023 225 333 / 1800 203 203",
    hours: "Open 24 hours (Smart Self-Banking)",
    hoursKh: "បម្រើ ២៤ ម៉ោង (ទូស្វ័យសេវា Smart Banking)",
    rating: 4.9,
    reviewsCount: 6500,
    distance: "1.4 km away",
    distanceKh: "១.៤ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=700&auto=format&fit=crop&q=80",
    description: "Cambodia's leading digital bank providing instant cash deposit/withdrawal ATMs, card issuance machines, international transfers, and 24/7 smart banking.",
    descriptionKh: "ធនាគារឌីជីថលឈានមុខគេនៅកម្ពុជា មានទូដក/ដាក់ប្រាក់ភ្លាមៗ ទូបោះពុម្ពកាតដោយខ្លួនឯង និងសេវាធនាគារ ២៤ម៉ោង។",
    website: "https://www.ababank.com",
    lat: 11.5540,
    lng: 104.9280,
    mapQuery: "ABA+Bank+Head+Office+Phnom+Penh"
  },
  {
    id: "bank-acleda-hq",
    name: "ACLEDA Bank Plc. Headquarters",
    nameKh: "ធនាគារ អេស៊ីលីដា ភីអិលស៊ី (ទីស្នាក់ការកណ្តាល)",
    category: "banks",
    categoryLabel: "National Commercial Bank",
    categoryLabelKh: "ធនាគារពាណិជ្ជធំជាងគេ",
    categoryIcon: "fa-solid fa-money-check-dollar",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Toul Kork",
    districtKh: "ខណ្ឌទួលគោក",
    address: "#61 Monivong Blvd, Sangkat Srah Chak, Khan Daun Penh, Phnom Penh",
    addressKh: "អគារលេខ ៦១ មហាវិថីព្រះមុនីវង្ស សង្កាត់ស្រះចក ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "023 999 999",
    hours: "07:30 AM - 04:30 PM (ATMs 24/7)",
    hoursKh: "០៧:៣០ ព្រឹក - ០៤:៣០ ល្ងាច (ATM ២៤ម៉ោង)",
    rating: 4.8,
    reviewsCount: 4200,
    distance: "0.7 km away",
    distanceKh: "០.៧ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=700&auto=format&fit=crop&q=80",
    description: "The largest domestic bank with nationwide branches across all 25 provinces, offering comprehensive trade finance, payroll, loans, and Bakong QR payments.",
    descriptionKh: "ធនាគារក្នុងស្រុកធំជាងគេ មានសាខាគ្រប់ខេត្តទាំង២៥ ទូទាំងប្រទេសកម្ពុជា ផ្តល់សេវាឥណទាន ប្រាក់បញ្ញើ និងការទូទាត់ Bakong KHQR។",
    website: "https://www.acledabank.com.kh",
    lat: 11.5810,
    lng: 104.9180,
    mapQuery: "ACLEDA+Bank+Headquarters+Phnom+Penh"
  },

  // 6. UNIVERSITIES & TRAINING CENTERS
  {
    id: "univ-rupp",
    name: "Royal University of Phnom Penh (RUPP)",
    nameKh: "សាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ (ស.ភ.ភ.)",
    category: "universities",
    categoryLabel: "National Public University",
    categoryLabelKh: "សាកលវិទ្យាល័យរដ្ឋចំណាស់ជាងគេ",
    categoryIcon: "fa-solid fa-graduation-cap",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Toul Kork",
    districtKh: "ខណ្ឌទួលគោក",
    address: "Russian Federation Blvd, Sangkat Teuk Laak I, Khan Toul Kork, Phnom Penh",
    addressKh: "មហាវិថីសហព័ន្ធរុស្ស៊ី សង្កាត់ទឹកល្អក់ទី១ ខណ្ឌទួលគោក រាជធានីភ្នំពេញ",
    phone: "023 883 640",
    hours: "07:30 AM - 05:30 PM",
    hoursKh: "០៧:៣០ ព្រឹក - ០៥:៣០ ល្ងាច",
    rating: 4.9,
    reviewsCount: 5100,
    distance: "3.5 km away",
    distanceKh: "៣.៥ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=700&auto=format&fit=crop&q=80",
    description: "Cambodia's oldest and largest public university, founded in 1960, offering degrees in Sciences, Engineering, Humanities, Computer Science, and Foreign Languages (IFL).",
    descriptionKh: "សាកលវិទ្យាល័យរដ្ឋធំ និងចំណាស់ជាងគេនៅកម្ពុជា បង្កើតឡើងក្នុងឆ្នាំ១៩៦០ បណ្តុះបណ្តាលវិទ្យាសាស្ត្រ វិស្វកម្ម ព័ត៌មានវិទ្យា និងវិទ្យាស្ថានភាសាបរទេស (IFL)។",
    website: "http://www.rupp.edu.kh",
    lat: 11.5680,
    lng: 104.8910,
    mapQuery: "Royal+University+of+Phnom+Penh"
  },
  {
    id: "train-pse",
    name: "Pour un Sourire d'Enfant (PSE Institute)",
    nameKh: "អង្គការ និងវិទ្យាស្ថានបណ្តុះបណ្តាល ភាពញញឹមនៃកុមារ (PSE)",
    category: "training",
    categoryLabel: "Vocational & Technical Institute",
    categoryLabelKh: "វិទ្យាស្ថានបណ្តុះបណ្តាលវិជ្ជាជីវៈ",
    categoryIcon: "fa-solid fa-chalkboard-user",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Meanchey",
    districtKh: "ខណ្ឌមានជ័យ",
    address: "#402 Trea Village, Sangkat Stung Meanchey, Khan Meanchey, Phnom Penh",
    addressKh: "អគារលេខ ៤០២ ភូមិទ្រា សង្កាត់ស្ទឹងមានជ័យ ខណ្ឌមានជ័យ រាជធានីភ្នំពេញ",
    phone: "023 995 660",
    hours: "08:00 AM - 05:00 PM",
    hoursKh: "០៨:០០ ព្រឹក - ០៥:០០ ល្ងាច",
    rating: 5.0,
    reviewsCount: 1890,
    distance: "4.8 km away",
    distanceKh: "៤.៨ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=700&auto=format&fit=crop&q=80",
    description: "Acclaimed vocational training institute empowering youth with certified skills in Hospitality, Culinary Arts, Digital Tech, Mechanics, Construction, and Film.",
    descriptionKh: "វិទ្យាស្ថានបណ្តុះបណ្តាលវិជ្ជាជីវៈដ៏ល្បីល្បាញ បណ្តុះបណ្តាលជំនាញបដិសណ្ឋារកិច្ច វិស្វកម្ម ឌីជីថល សំណង់ និងសិល្បៈធ្វើម្ហូប។",
    website: "https://pse.ngo",
    lat: 11.5310,
    lng: 104.8960,
    mapQuery: "PSE+Institute+Phnom+Penh"
  },

  // 7. APARTMENTS & REAL ESTATE
  {
    id: "house-the-bridge",
    name: "The Bridge Residence (Tonle Bassac)",
    nameKh: "ខុនដូ ដឺប្រ៊ីដ (The Bridge Residence)",
    category: "housing",
    categoryLabel: "Luxury High-Rise Condominium",
    categoryLabelKh: "ខុនដូប្រណីតកណ្តាលក្រុង",
    categoryIcon: "fa-solid fa-building",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Chamkarmon",
    districtKh: "ខណ្ឌចំការមន",
    address: "National Assembly Blvd, Sangkat Tonle Bassac, Khan Chamkarmon, Phnom Penh",
    addressKh: "មហាវិថីរដ្ឋសភា សង្កាត់ទន្លេបាសាក់ ខណ្ឌចំការមន រាជធានីភ្នំពេញ",
    phone: "023 900 888",
    hours: "24/7 Security & Concierge",
    hoursKh: "សន្តិសុខ & សេវាកម្ម ២៤/៧",
    rating: 4.7,
    reviewsCount: 1530,
    distance: "2.2 km away",
    distanceKh: "២.២ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&auto=format&fit=crop&q=80",
    description: "45-storey landmark mixed development near the Australian Embassy and Diamond Island, featuring studio to 3-bedroom units, infinity pool, gym, and retail stores.",
    descriptionKh: "ខុនដូកម្ពស់ ៤៥ជាន់ នៅក្បែរកោះពេជ្រ និងស្ថានទូតអូស្ត្រាលី មានបន្ទប់ស្ទូឌីយោ អាងហែលទឹកលើអាកាស ក្លឹបហាត់ប្រាណ និងផ្សារទំនិញ។",
    website: "https://oxleyworldbridge.com.kh",
    lat: 11.5480,
    lng: 104.9380,
    mapQuery: "The+Bridge+Residence+Phnom+Penh"
  },
  {
    id: "house-urban-village",
    name: "Urban Village Phnom Penh (Hun Sen Blvd)",
    nameKh: "ខុនដូ អឺបាន វីលេច (Urban Village)",
    category: "housing",
    categoryLabel: "Modern Community Condominium",
    categoryLabelKh: "ខុនដូសហគមន៍ទំនើប",
    categoryIcon: "fa-solid fa-house-chimney",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Meanchey",
    districtKh: "ខណ្ឌមានជ័យ",
    address: "Samdech Hun Sen Blvd (St. 60m), Sangkat Chak Angre Leu, Phnom Penh",
    addressKh: "មហាវិថីសម្តេច ហ៊ុន សែន (ផ្លូវ ៦០ម៉ែត្រ) សង្កាត់ចាក់អង្រែលើ រាជធានីភ្នំពេញ",
    phone: "017 999 088",
    hours: "08:00 AM - 07:00 PM (Showroom)",
    hoursKh: "០៨:០០ ព្រឹក - ០៧:០០ យប់",
    rating: 4.8,
    reviewsCount: 1120,
    distance: "4.8 km away",
    distanceKh: "៤.៨ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=700&auto=format&fit=crop&q=80",
    description: "Award-winning residential community connected to Factory Phnom Penh creative hub, offering green open parks, co-working spaces, and modern lifestyle amenities.",
    descriptionKh: "គម្រោងខុនដូទទួលបានពានរង្វាន់អន្តរជាតិ ភ្ជាប់ជាមួយ Factory Phnom Penh មានសួនបៃតង កន្លែងធ្វើការ Co-working និងបរិស្ថានរស់នៅបែបយុវវ័យ។",
    website: "https://urbanvillage.com.kh",
    lat: 11.5230,
    lng: 104.9310,
    mapQuery: "Urban+Village+Phnom+Penh"
  },

  // 8. TOURIST ATTRACTIONS & LANDMARKS
  {
    id: "tour-angkor-wat",
    name: "Angkor Wat Temple",
    nameKh: "ប្រាសាទអង្គរវត្ត",
    category: "tourist",
    categoryLabel: "UNESCO World Heritage Site",
    categoryLabelKh: "សម្បត្តិបេតិកភណ្ឌពិភពលោក UNESCO",
    categoryIcon: "fa-solid fa-landmark-dome",
    province: "Siem Reap",
    provinceKh: "ខេត្តសៀមរាប",
    district: "Angkor Archaeological Park",
    districtKh: "ឧទ្យានបុរាណវិទ្យាអង្គរ",
    address: "Angkor Archaeological Park, Siem Reap Province, Cambodia",
    addressKh: "ឧទ្យានបុរាណវិទ្យាអង្គរ ខេត្តសៀមរាប ព្រះរាជាណាចក្រកម្ពុជា",
    phone: "063 760 012",
    hours: "05:00 AM - 05:30 PM (Sunrise entry)",
    hoursKh: "០៥:០០ ព្រឹក - ០៥:៣០ ល្ងាច (មើលថ្ងៃរះ)",
    rating: 5.0,
    reviewsCount: 28900,
    distance: "Siem Reap Province",
    distanceKh: "ខេត្តសៀមរាប",
    image: "./src/assets/angkor_wat_hero.jpg",
    description: "The largest religious monument in the world and the national pride of Cambodia, constructed in the early 12th century by King Suryavarman II.",
    descriptionKh: "សំណង់សាសនាដ៏ធំបំផុតនៅលើពិភពលោក និងជាមោទនភាពជាតិខ្មែរ កសាងឡើងក្នុងសតវត្សរ៍ទី១២ ដោយព្រះបាទសូរ្យវរ្ម័នទី២។",
    website: "https://angkorenterprise.gov.kh",
    lat: 13.4125,
    lng: 103.8670,
    mapQuery: "Angkor+Wat+Siem+Reap"
  },
  {
    id: "tour-royal-palace",
    name: "Royal Palace of Cambodia & Silver Pagoda",
    nameKh: "ព្រះបរមរាជវាំង & វត្តព្រះកែវមរកត",
    category: "tourist",
    categoryLabel: "Royal Heritage & Landmark",
    categoryLabelKh: "ព្រះបរមរាជវាំងប្រវត្តិសាស្ត្រ",
    categoryIcon: "fa-solid fa-crown",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "Samdech Sothearos Blvd, Sangkat Chey Chumneas, Khan Daun Penh, Phnom Penh",
    addressKh: "មហាវិថីសម្តេចសុធារស សង្កាត់ជ័យជំនះ ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "023 217 566",
    hours: "08:00 AM - 11:00 AM, 02:00 PM - 05:00 PM",
    hoursKh: "០៨:០០ - ១១:០០ ព្រឹក, ០២:០០ - ០៥:០០ ល្ងាច",
    rating: 4.8,
    reviewsCount: 7800,
    distance: "1.0 km away",
    distanceKh: "១.០ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=700&auto=format&fit=crop&q=80",
    description: "The official royal residence of His Majesty King Norodom Sihamoni, showcasing classic Khmer architecture, manicured gardens, and the Silver Pagoda with 5,000 silver floor tiles.",
    descriptionKh: "ព្រះរាជដំណាក់ផ្លូវការនៃព្រះករុណាព្រះបាទសម្តេចព្រះបរមនាថ នរោត្តម សីហមុនី បង្ហាញស្ថាបត្យកម្មខ្មែរដ៏វិចិត្រ និងវត្តព្រះកែវមរកតក្រាលដោយការ៉ូប្រាក់សុទ្ធជាង ៥,០០០បន្ទះ។",
    website: "http://www.tourismcambodia.org",
    lat: 11.5630,
    lng: 104.9315,
    mapQuery: "Royal+Palace+Phnom+Penh"
  },
  {
    id: "tour-bokor-mountain",
    name: "Preah Monivong Bokor National Park",
    nameKh: "ឧទ្យានជាតិព្រះមុនីវង្ស បូកគោ",
    category: "tourist",
    categoryLabel: "Mountain Park & Heritage",
    categoryLabelKh: "ឧទ្យានជាតិ & រមណីយដ្ឋានភ្នំបូកគោ",
    categoryIcon: "fa-solid fa-mountain-sun",
    province: "Kampot",
    provinceKh: "ខេត្តកំពត",
    district: "Tuek Chhou",
    districtKh: "ស្រុកទឹកឈូ",
    address: "Bokor Mountain Plateau, Kampot Province, Cambodia",
    addressKh: "ខ្ពង់រាបភ្នំបូកគោ ខេត្តកំពត ព្រះរាជាណាចក្រកម្ពុជា",
    phone: "033 688 888",
    hours: "Open daily (06:00 AM - 06:00 PM)",
    hoursKh: "បើកជារៀងរាល់ថ្ងៃ (០៦:០០ ព្រឹក - ០៦:០០ ល្ងាច)",
    rating: 4.8,
    reviewsCount: 4300,
    distance: "Kampot Province",
    distanceKh: "ខេត្តកំពត",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=700&auto=format&fit=crop&q=80",
    description: "Elevated highland park 1,080 meters above sea level, famous for cool misty breezes, French colonial palace ruins, Lok Yeay Mao monument, and scenic coastal panoramas.",
    descriptionKh: "ឧទ្យានជាតិកម្ពស់ ១,០៨០ម៉ែត្រលើនីវ៉ូទឹកសមុទ្រ មានអាកាសធាតុត្រជាក់ស្រស់ស្រាយ វិមានបារាំងបុរាណ រូបសំណាកលោកយាយម៉ៅ និងទេសភាពសមុទ្រដ៏ស្រស់ស្អាត។",
    website: "https://sokhahotels.com/bokor",
    lat: 10.6270,
    lng: 104.0250,
    mapQuery: "Bokor+National+Park+Kampot"
  },

  // 9. HOTELS & RESORTS
  {
    id: "hotel-raffles-le-royal",
    name: "Raffles Hotel Le Royal Phnom Penh",
    nameKh: "សណ្ឋាគារ រ៉ាហ្វល ឡឺ រ៉ូយ៉ាល់ (Raffles Hotel Le Royal)",
    category: "hotels",
    categoryLabel: "Historic 5-Star Luxury Hotel",
    categoryLabelKh: "សណ្ឋាគារប្រណីតកម្រិតផ្កាយ៥",
    categoryIcon: "fa-solid fa-hotel",
    province: "Phnom Penh",
    provinceKh: "រាជធានីភ្នំពេញ",
    district: "Daun Penh",
    districtKh: "ខណ្ឌដូនពេញ",
    address: "#92 Rukhak Vithei Daun Penh, Sangkat Wat Phnom, Phnom Penh",
    addressKh: "អគារលេខ ៩២ វិថីដូនពេញ សង្កាត់វត្តភ្នំ ខណ្ឌដូនពេញ រាជធានីភ្នំពេញ",
    phone: "023 981 888",
    hours: "24/7 Concierge & Reception",
    hoursKh: "បម្រើសេវា ២៤ ម៉ោង",
    rating: 4.9,
    reviewsCount: 2800,
    distance: "0.9 km away",
    distanceKh: "០.៩ គីឡូម៉ែត្រពីអ្នក",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&auto=format&fit=crop&q=80",
    description: "Phnom Penh's premier heritage hotel since 1929, hosting royalty, dignitaries, and travelers in timeless French-Khmer luxury surrounded by tropical gardens.",
    descriptionKh: "សណ្ឋាគារបេតិកភណ្ឌប្រវត្តិសាស្ត្រចំណាស់បំផុតនៅភ្នំពេញតាំងពីឆ្នាំ១៩២៩ បម្រើសេវាកម្មប្រណីតលំដាប់ពិភពលោក។",
    website: "https://www.raffles.com/phnom-penh/",
    lat: 11.5750,
    lng: 104.9190,
    mapQuery: "Raffles+Hotel+Le+Royal+Phnom+Penh"
  }
];

// =========================================================================
// INTERACTIVE 25 PROVINCES OF CAMBODIA DATASET
// =========================================================================
export const provincesData = [
  {
    id: "phnom-penh",
    name: "Phnom Penh",
    nameKh: "រាជធានីភ្នំពេញ",
    capital: "Phnom Penh Capital",
    capitalKh: "រាជធានីភ្នំពេញ",
    tagline: "The vibrant economic, cultural, and political heart of Cambodia",
    taglineKh: "បេះដូងសេដ្ឋកិច្ច វប្បធម៌ និងនយោបាយនៃព្រះរាជាណាចក្រកម្ពុជា",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Royal Palace & Silver Pagoda", nameKh: "ព្រះបរមរាជវាំង & វត្តព្រះកែវមរកត", desc: "Historic royal residence and national cultural symbol" },
      { name: "Wat Phnom Historical Sanctuary", nameKh: "រមណីយដ្ឋានប្រវត្តិសាស្ត្រវត្តភ្នំ", desc: "Foundational hill temple of the capital city" },
      { name: "National Museum of Cambodia", nameKh: "សារមន្ទីរជាតិកម្ពុជា", desc: "World's largest collection of ancient Khmer terracotta and bronze art" }
    ],
    hospitals: ["Calmette Hospital (023 426 948)", "Kantha Bopha Hospital (1288)", "Khmer-Soviet Friendship Hospital (023 217 764)"],
    restaurants: ["Malis Restaurant (Norodom Blvd)", "Romdeng Restaurant", "Brown Coffee Roastery BKK1"],
    hotels: ["Raffles Hotel Le Royal", "Rosewood Phnom Penh (Vattanac Tower)", "Sofitel Phnom Penh Phokeethra"],
    jobs: ["Banking & FinTech (ABA, ACLEDA, Wing)", "Software Engineers (CamTech)", "Telecom & Corporate (Smart, Cellcard)"],
    housing: ["The Bridge Residence (Tonle Bassac)", "Urban Village (Hun Sen Blvd)", "Borey Peng Huoth Grand Star"],
    education: ["Royal University of Phnom Penh (RUPP)", "Institute of Technology of Cambodia (ITC)", "PSE Institute"],
    transportation: ["Phnom Penh City Bus Lines 1-4", "Royal Railway Central Station", "PassApp & Grab ride-hailing"]
  },
  {
    id: "siem-reap",
    name: "Siem Reap",
    nameKh: "ខេត្តសៀមរាប",
    capital: "Siem Reap City",
    capitalKh: "ក្រុងសៀមរាប",
    tagline: "Gateway to the majestic UNESCO Angkor World Heritage Archaeological Park",
    taglineKh: "ទឹកដីបេតិកភណ្ឌពិភពលោកអង្គរដ៏មហស្ចារ្យ និងជាទីក្រុងទេសចរណ៍លំដាប់អន្តរជាតិ",
    image: "./src/assets/angkor_wat_hero.jpg",
    attractions: [
      { name: "Angkor Wat Temple", nameKh: "ប្រាសាទអង្គរវត្ត", desc: "World's largest temple monument and sunrise wonder" },
      { name: "Bayon Temple & Angkor Thom", nameKh: "ប្រាសាទបាយ័ន (មុខព្រហ្ម ៤)", desc: "Enigmatic smiling stone faces of Avalokiteshvara" },
      { name: "Ta Prohm Temple (Tomb Raider)", nameKh: "ប្រាសាទតាព្រហ្ម", desc: "Ancient stone towers embraced by giant silk-cotton trees" },
      { name: "Phnom Kulen Waterfall & River of Thousand Lingas", nameKh: "ភ្នំគូលែន & ស្ទឹងលិង្គមួយពាន់", desc: "Sacred mountain plateau and origin of the Khmer Empire" }
    ],
    hospitals: ["Jayavarman VII Children Hospital (Kantha Bopha 3)", "Siem Reap Provincial Referral Hospital (063 760 119)", "Royal Angkor International Hospital"],
    restaurants: ["Haven Restaurant (Wat Damnak)", "Cuisine Wat Damnak (Michelin-recognized)", "Chanrey Tree Khmer Cuisine"],
    hotels: ["Victoria Angkor Resort & Spa", "FCC Angkor by Avani", "Raffles Grand Hotel d'Angkor"],
    jobs: ["Hospitality & Eco-Tourism Management", "Archaeological Conservation", "Agri-Tourism & Craft Enterprises"],
    housing: ["Wat Bo Heritage Villas", "Sala Kamreuk Residential Condos", "Svay Dangkum Eco-Houses"],
    education: ["Paññāsāstra University Siem Reap", "Build Bright University Siem Reap", "Sala Baï Hotel School"],
    transportation: ["Siem Reap Angkor International Airport (SAI)", "Giant Ibis Express Terminal", "Electric Angkor Shuttles"]
  },
  {
    id: "takeo",
    name: "Takeo",
    nameKh: "ខេត្តតាកែវ",
    capital: "Doun Kaev City",
    capitalKh: "ក្រុងដូនកែវ",
    tagline: "Cradle of Khmer civilization, home to Funan Kingdom ruins and pristine lakes",
    taglineKh: "ទឹកដីកំណើតអារ្យធម៌ខ្មែរ អាណាចក្រភ្នំ និងប្រាសាទបុរាណចំណាស់ៗ",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Phnom Da Temple & Ashram Maha Rosei", nameKh: "ប្រាសាទភ្នំដា & អាស្រមមហាឫសី", desc: "6th-century Funan era brick temples and canal waterways" },
      { name: "Ta Prohm Temple of Tonle Bati", nameKh: "ប្រាសាទតាព្រហ្ម ទន្លេបាទី", desc: "Late 12th-century Jayavarman VII sandstone temple on scenic lakeside" },
      { name: "Phnom Tamao Wildlife Rescue Centre", nameKh: "ឧទ្យានសត្វ និងមជ្ឈមណ្ឌលសង្គ្រោះសត្វព្រៃភ្នំតាម៉ៅ", desc: "Largest wildlife sanctuary in Cambodia protecting endangered species" },
      { name: "Angkor Borei Archaeological Museum", nameKh: "សារមន្ទីរបុរាណវិទ្យាអង្គរបុរី", desc: "Historic capital of the ancient pre-Angkorian Funan civilization" }
    ],
    hospitals: ["Takeo Provincial Referral Hospital (032 931 224)", "Ang Roka District Hospital", "Bati District Health Center"],
    restaurants: ["Phnom Tamao Roasted Chicken Stalls", "Tonle Bati Floating Bamboo Pavilions", "Doun Kaev Riverview Eateries"],
    hotels: ["Alice Villa Hotel Takeo", "Doun Kaev Guesthouse", "Tonle Bati Eco Resort"],
    jobs: ["Silk Weaving & Artisans (Hol Takeo)", "Agriculture & Aquaculture Supply", "Eco-Tourism & Heritage Guides"],
    housing: ["Doun Kaev Waterfront Residences", "Bati Town Modern Shophouses", "Takeo Green Farmhouses"],
    education: ["Takeo Regional Teacher Training Center", "Chea Sim University of Kamchaymear Takeo Branch"],
    transportation: ["National Road 2 Express Vans", "Royal Railway Takeo Station", "Takeo Canal Boat Taxis to Angkor Borei"]
  },
  {
    id: "kampot",
    name: "Kampot",
    nameKh: "ខេត្តកំពត",
    capital: "Kampot City",
    capitalKh: "ក្រុងកំពត",
    tagline: "Famous for world-renowned GI Kampot Pepper, Bokor Mountain, and tranquil rivers",
    taglineKh: "ទឹកដីម្រេចកំពតល្បីលំដាប់ពិភពលោក ភ្នំបូកគោ និងដងព្រែកទឹកឈូដ៏មនោរម្យ",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Bokor Mountain National Park", nameKh: "ឧទ្យានជាតិភ្នំបូកគោ", desc: "Misty 1,080m mountain plateau with French Palace ruins" },
      { name: "La Plantation GI Kampot Pepper Farm", nameKh: "ចម្ការម្រេចឡាផ្លានថេសិន", desc: "Organic certified black, red, and white pepper plantation" },
      { name: "Tuek Chhou Rapids & Green River", nameKh: "រមណីយដ្ឋានទឹកឈូ & ព្រែកកំពត", desc: "Clear river swimming, kayaking, and sunset cruises" },
      { name: "Phnom Chhngok Hindu Cave Temple", nameKh: "ប្រាសាទរូងភ្នំឈ្ងោក", desc: "7th-century brick Shiva temple built inside natural limestone caves" }
    ],
    hospitals: ["Kampot Provincial Referral Hospital (033 932 546)", "Sonja Kill Memorial Hospital (High standard pediatric & general)"],
    restaurants: ["Rikitikitavi Riverfront Restaurant", "Twenty Three Kampot Bistro", "Bokor Mountain Panorama Cafe"],
    hotels: ["Le Bokor Palace (Historic 5-Star)", "Kampot River Bungalows", "Castle Bayview Resort"],
    jobs: ["Agri-Business & Organic Pepper Export", "River Hospitality & Eco-Lodges", "Salt Production Operations"],
    housing: ["Kampot Riverside Heritage Villas", "Tuek Chhou Orchard Land", "Kampot New Town Shophouses"],
    education: ["Kampot Regional Polytechnic Institute", "Chea Sim University Kampot Campus"],
    transportation: ["Royal Railway Train (Phnom Penh ⇄ Kampot)", "Giant Ibis & Champa Express Vans", "Kampot International Tourism Port"]
  },
  {
    id: "battambang",
    name: "Battambang",
    nameKh: "ខេត្តបាត់ដំបង",
    capital: "Battambang City",
    capitalKh: "ក្រុងបាត់ដំបង",
    tagline: "Cambodia's rice bowl, famous for French colonial architecture, arts, and bamboo train",
    taglineKh: "ជង្រុកស្រូវនៃប្រទេសកម្ពុជា សម្បូរផ្ទះបារាំងបុរាណ សិល្បៈ និងរថភ្លើងឫស្សី (ណូរី)",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Phnom Sampeau & Bat Cave Phenomenon", nameKh: "ភ្នំសំពៅ & ល្អាងសត្វប្រចៀវរាប់លាន", desc: "Millions of bats flying at sunset in hypnotic waves" },
      { name: "Authentic Bamboo Train (Norry)", nameKh: "រថភ្លើងឫស្សី (ណូរីបាត់ដំបង)", desc: "Unique improvised railway ride through countryside landscapes" },
      { name: "Ek Phnom & Banan Ancient Temples", nameKh: "ប្រាសាទឯកភ្នំ & ប្រាសាទបាណន់", desc: "11th-century Angkorian stone sanctuaries perched on hills" },
      { name: "Phare Ponleu Selpak Circus & Art Academy", nameKh: "ហ្វារពន្លឺសិល្បៈ បាត់ដំបង", desc: "Internationally acclaimed performing arts and circus school" }
    ],
    hospitals: ["Battambang Provincial Referral Hospital (053 952 822)", "Emergency Hospital Battambang", "World Food Program Clinic"],
    restaurants: ["Jaan Bai Social Restaurant", "White Rose Bakery & Khmer Food", "Choco L'Art Cafe"],
    hotels: ["Bambu Hotel Battambang", "Classy Hotel & Spa", "Maisons Wat Kor Heritage Resort"],
    jobs: ["Agri-Tech & Jasmine Rice Export (Phsar Thom)", "Phare Arts & Creative Industry", "Cross-Border Commerce"],
    housing: ["Sangke Riverfront Colonial Homes", "Wat Kor Eco Villas", "Battambang Green Subdivisions"],
    education: ["National Battambang University (NBU)", "University of Battambang (UBB)", "Phare Art Academy"],
    transportation: ["Royal Railway Northern Line Train", "Capitol Tour & Virak Buntham Terminals", "Battambang-Siem Reap Scenic River Boats"]
  },
  {
    id: "sihanoukville",
    name: "Preah Sihanouk (Sihanoukville)",
    nameKh: "ខេត្តព្រះសីហនុ",
    capital: "Sihanoukville City",
    capitalKh: "ក្រុងព្រះសីហនុ",
    tagline: "Cambodia's deep-sea port city and gateway to tropical islands like Koh Rong",
    taglineKh: "ទីក្រុងកំពង់ផែសមុទ្រទឹកជ្រៅ និងច្រកទ្វារទៅកាន់កោះឋានសួគ៌កោះរ៉ុង",
    image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Koh Rong & Koh Rong Sanloem Islands", nameKh: "កោះរ៉ុង & កោះរ៉ុងសន្លឹម", desc: "White sand beaches, bioluminescent plankton, and turquoise waters" },
      { name: "Otres Beach & Ochheuteal Beach", nameKh: "ឆ្នេរអូរត្រេះ & ឆ្នេរអូរឈើទាល", desc: "Stunning coastal promenades and sunset beachfront dining" },
      { name: "Ream National Park & Mangrove Forests", nameKh: "ឧទ្យានជាតិរាម & ព្រៃកោងកាង", desc: "Protected wildlife sanctuary, marine reserves, and waterfalls" }
    ],
    hospitals: ["Sihanoukville Referral Hospital (034 933 605)", "Sihanoukville International Clinic", "Sun International Clinic"],
    restaurants: ["The Secret Garden Otres Beach", "Starfish Bakery & Cafe", "Koh Rong Seafood Grills"],
    hotels: ["The Royal Sands Koh Rong (5-Star Luxury)", "Independence Hotel Resort & Spa", "Sokha Beach Resort"],
    jobs: ["Deep Sea Port Logistics (PAS)", "Special Economic Zone (PPSEZ & SSEZ)", "Island Luxury Eco-Resorts"],
    housing: ["Otres Beachfront Condominiums", "City Center Modern High-Rises", "Ream Coastal Eco-Villas"],
    education: ["Life University Sihanoukville", "National Management Institute Sihanoukville"],
    transportation: ["Sihanoukville Autonomous Port Ferry Terminal", "Phnom Penh - Sihanoukville Expressway (1.5 hrs)", "Sihanoukville International Airport (KOS)"]
  },
  {
    id: "kep",
    name: "Kep",
    nameKh: "ខេត្តកែប",
    capital: "Kep City",
    capitalKh: "ក្រុងកែប",
    tagline: "Charming seaside retreat famous for blue swimmer crabs, French villas, and national park",
    taglineKh: "ទីក្រុងទេសចរណ៍មាត់សមុទ្រដ៏ស្ងប់ស្ងាត់ ល្បីល្បាញដោយក្តាមសេះ និងម្ហូបសមុទ្រស្រស់ៗ",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Kep Crab Market (Phsar Kdam)", nameKh: "ផ្សារក្តាមខេត្តកែប", desc: "Fresh blue swimmer crab cooked directly with fresh Kampot green pepper" },
      { name: "Kep National Park & Sunset Rock", nameKh: "ឧទ្យានជាតិកែប", desc: "8km scenic mountain jungle trail with sweeping Gulf of Thailand ocean views" },
      { name: "Koh Tonsay (Rabbit Island)", nameKh: "កោះទន្សាយ", desc: "Idyllic untouched tropical island just 20 minutes boat ride from Kep pier" }
    ],
    hospitals: ["Kep Provincial Health Center (036 633 688)", "Kampot Referral Hospital (15 mins away)"],
    restaurants: ["Kimly Seafood Crab Market", "La Baraka French-Khmer Lounge", "The Sailing Club Kep"],
    hotels: ["Knai Bang Chatt Luxury Resort", "Veranda Natural Resort", "Samanea Beach Resort"],
    jobs: ["Artisan Marine Fisheries", "Boutique Eco-Lodge Management", "National Park Eco-Tourism"],
    housing: ["Kep Hillside Oceanview Villas", "Crab Market Commercial Plots", "Rabbit Island Eco-Stays"],
    education: ["Don Bosco Technical School Kep", "Kep Provincial High School"],
    transportation: ["Kep Tourism Pier to Rabbit Island", "Express Coastal Minivans", "Scenic Coastal Highway to Vietnam Border"]
  },
  {
    id: "mondulkiri",
    name: "Mondulkiri",
    nameKh: "ខេត្តមណ្ឌលគិរី",
    capital: "Sen Monorom City",
    capitalKh: "ក្រុងសែនមនោរម្យ",
    tagline: "Highland sanctuary of pine forests, rolling green hills, waterfalls, and protected elephants",
    taglineKh: "ទឹកដីខ្ពង់រាបពោរពេញដោយព្រៃស្រល់ ភ្នំស្មៅបៃតង ទឹកធ្លាក់ប៊ូស្រា និងជម្រកដំរីព្រៃ",
    image: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Bousra Majestic Waterfall", nameKh: "ទឹកធ្លាក់ប៊ូស្រា", desc: "Cambodia's most famous multi-tiered roaring waterfall nestled in dense jungle" },
      { name: "Elephant Valley Project Sanctuary", nameKh: "គម្រោងអភិរក្សដំរីព្រៃអេឡេហ្វិនវ៉ាលី (EVP)", desc: "Ethical wildlife sanctuary where rescued Asian elephants roam freely" },
      { name: "Sea Forest (Samot Chhoeu Plateau)", nameKh: "សមុទ្រឈើ (ខ្ពង់រាបសែនមនោរម្យ)", desc: "Endless canopy of green tropical forests stretching beyond the horizon" }
    ],
    hospitals: ["Mondulkiri Provincial Referral Hospital (073 952 119)", "Sen Monorom Health Clinic"],
    restaurants: ["Mondulkiri Pizza & Coffee Roasters", "Indigenous Bunong Traditional Kitchen", "Green House Cafe"],
    hotels: ["Nature Lodge Eco Resort", "Mayura Hill Resort", "Tree Top Lodge Mondulkiri"],
    jobs: ["Organic Mondulkiri Coffee & Avocado Farming", "Ethical Wildlife Conservation", "Indigenous Cultural Heritage"],
    housing: ["Pine Forest Mountain Cabins", "Sen Monorom Hillside Farmsteads", "Eco-Homestead Land"],
    education: ["Sen Monorom Regional High School", "Bunong Cultural Training Institute"],
    transportation: ["Vireak Buntham & Kim Seng Express", "Highland 4x4 Eco Transport", "Sen Monorom Airfield Link"]
  },
  {
    id: "kandal",
    name: "Kandal",
    nameKh: "ខេត្តកណ្តាល",
    capital: "Ta Khmao City",
    capitalKh: "ក្រុងតាខ្មៅ",
    tagline: "Surrounding the capital with Mekong river islands, Koh Dach silk, and Udong heritage",
    taglineKh: "ខេត្តព័ទ្ធជុំវិញរាជធានី សម្បូរដោយភ្នំព្រះរាជទ្រព្យ (ឧដុង្គ) និងកោះដាច់តម្បាញសូត្រ",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Oudong Mountain (Phnom Preah Reach Troap)", nameKh: "ភ្នំឧដុង្គ (ភ្នំព្រះរាជទ្រព្យ)", desc: "Historic royal necropolis of ancient Cambodian kings with gold stupas" },
      { name: "Koh Dach Silk Weaving Island", nameKh: "កោះដាច់ (ភូមិតម្បាញសូត្រខ្មែរ)", desc: "Scenic Mekong river island where artisans hand-weave authentic Khmer silk" }
    ],
    hospitals: ["Victory Hospital Ta Khmao", "Kandal Provincial Referral Hospital (024 985 222)"],
    restaurants: ["Ta Khmao Riverside Fish Grills", "Koh Dach Floating Bamboo Stalls", "Udong Mountain Specialty Stalls"],
    hotels: ["Ta Khmao Riverside Hotel", "Koh Dach Silk Farm Homestays"],
    jobs: ["Industrial Manufacturing & Garments", "Mekong Agri-Food Supply", "Silk Craftsmanship"],
    housing: ["Borey Grand Ta Khmao", "Arey Ksat Riverfront Residences", "Udong Expressway Land"],
    education: ["Ta Khmao Regional Institute", "Kandal Teacher Training College"],
    transportation: ["Phnom Penh City Bus Line 2 (To Ta Khmao)", "Arey Ksat River Ferry", "Techo Takhmao International Airport (TIA)"]
  },
  {
    id: "kampong-cham",
    name: "Kampong Cham",
    nameKh: "ខេត្តកំពង់ចាម",
    capital: "Kampong Cham City",
    capitalKh: "ក្រុងកំពង់ចាម",
    tagline: "Historic Mekong trading city with iconic bamboo bridge and rubber plantations",
    taglineKh: "ទីក្រុងមាត់ទន្លេមេគង្គប្រវត្តិសាស្ត្រ ល្បីល្បាញដោយស្ពានឫស្សីកោះប៉ែន និងចម្ការកៅស៊ូជប់",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Koh Paen Bamboo Bridge & Eco Village", nameKh: "ស្ពានឫស្សីកោះប៉ែន", desc: "Hand-built bamboo bridge reconstructed annually across the Mekong" },
      { name: "Wat Nokor Bachey Ancient Temple", nameKh: "វត្តនគរបាជ័យ", desc: "11th-century sandstone temple seamlessly integrated with modern pagoda" }
    ],
    hospitals: ["Kampong Cham Provincial Hospital (042 941 262)", "Mekong Health Clinic"],
    restaurants: ["Mekong Crossing River Cafe", "Destiny Coffee", "Hao An Seafood Kampong Cham"],
    hotels: ["LBN Asian Hotel", "Monorom VIP Hotel", "Mekong Hotel Kampong Cham"],
    jobs: ["Rubber & Cashew Nut Agro-Processing", "River Commercial Shipping", "Hospitality"],
    housing: ["Mekong Riverfront Shophouses", "Chhub Residential Properties", "Koh Paen Eco-Plots"],
    education: ["University of Management and Economics (UME Kampong Cham)", "Western University Kampong Cham"],
    transportation: ["Kizuna Bridge Crossing", "National Road 6 & 7 Express Buses", "Mekong River Passenger Boats"]
  },
  {
    id: "kampong-chhnang",
    name: "Kampong Chhnang",
    nameKh: "ខេត្តកំពង់ឆ្នាំង",
    capital: "Kampong Chhnang City",
    capitalKh: "ក្រុងកំពង់ឆ្នាំង",
    tagline: "Renowned for traditional handmade terracotta pottery and Tonle Sap floating villages",
    taglineKh: "ទឹកដីកុលាលភាជន៍ឆ្នាំងដីបុរាណ និងភូមិបណ្តែតទឹកបឹងទន្លេសាបដ៏ធំល្វឹងល្វើយ",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Andong Russei Traditional Pottery Village", nameKh: "ភូមិកុលាលភាជន៍អណ្តូងឫស្សី", desc: "Artisans shaping clay pottery by hand using ancestral techniques" },
      { name: "Chhnoc Tru Tonle Sap Floating Village", nameKh: "ភូមិបណ្តែតទឹកឆ្នុកទ្រូ", desc: "Bustling floating schools, markets, and pagodas on the great lake" }
    ],
    hospitals: ["Kampong Chhnang Provincial Referral Hospital (026 988 642)"],
    restaurants: ["Mekong Giant River Prawn Grills", "Tonle Sap Fish Soup Stalls"],
    hotels: ["Garden Guesthouse Kampong Chhnang", "Phoum Thmey Hotel"],
    jobs: ["Clay Pottery Artisanship", "Tonle Sap Fisheries & Dried Fish Export"],
    housing: ["Kampong Chhnang Riverside Subdivisions", "National Road 5 Shophouses"],
    education: ["Kampong Chhnang Provincial Technical Training Institute"],
    transportation: ["National Road 5 Expressway Links", "Tonle Sap Water Taxis"]
  },
  {
    id: "kampong-speu",
    name: "Kampong Speu",
    nameKh: "ខេត្តកំពង់ស្ពឺ",
    capital: "Chbar Mon City",
    capitalKh: "ក្រុងច្បារមន",
    tagline: "Famous for GI Palm Sugar, Phnom Aural (Cambodia's highest peak), and Kirirom pines",
    taglineKh: "ទឹកដីស្ករត្នោតកំពង់ស្ពឺល្បីលំដាប់ពិភពលោក ភ្នំឱរ៉ាល់ និងឧទ្យានជាតិគិរីរម្យ",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Kirirom National Park & Pine Forest", nameKh: "ឧទ្យានជាតិព្រះសុរាម្រិត-កុសមៈ គិរីរម្យ", desc: "Cool high-altitude pine plateau, waterfalls, and cliff views" },
      { name: "Phnom Aural (Highest Peak: 1,813m)", nameKh: "ភ្នំឱរ៉ាល់ (កំពូលភ្នំខ្ពស់បំផុតនៅកម្ពុជា)", desc: "Cambodia's tallest mountain, paradise for hikers and biodiversity" }
    ],
    hospitals: ["Kampong Speu Provincial Hospital (025 987 231)"],
    restaurants: ["Kirirom Pine Breeze Barbecue", "Kampong Speu Palm Juice Refreshments"],
    hotels: ["vKirirom Pine Resort (Luxury Glamping)", "Chbar Mon Palace Hotel"],
    jobs: ["GI Palm Sugar Processing", "Industrial Manufacturing Corridor", "Eco-Trekking Guides"],
    housing: ["Chbar Mon Modern Townhouses", "Kirirom Mountain Leisure Plots"],
    education: ["Kirirom Institute of Technology (KIT - Software Engineering)"],
    transportation: ["Phnom Penh - Sihanoukville Expressway Exit", "National Road 4 Highway"]
  },
  {
    id: "kampong-thom",
    name: "Kampong Thom",
    nameKh: "ខេត្តកំពង់ធំ",
    capital: "Stung Saen City",
    capitalKh: "ក្រុងស្ទឹងសែន",
    tagline: "Home to Sambor Prei Kuk, 7th-century pre-Angkorian brick temple World Heritage",
    taglineKh: "ទឹកដីសម្បត្តិបេតិកភណ្ឌពិភពលោកប្រាសាទសំបូរព្រៃគុក និងស្ទឹងសែនមនោរម្យ",
    image: "https://images.unsplash.com/photo-1541888946425-d0fbb18f15f7?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Sambor Prei Kuk UNESCO World Heritage Site", nameKh: "រមណីយដ្ឋានប្រាសាទសំបូរព្រៃគុក", desc: "Ancient 7th-century Chenla capital with octagonal brick temples in forest" },
      { name: "Phnom Santuk Holy Mountain", nameKh: "ភ្នំសន្ទុក", desc: "809-step sacred hill with giant reclining Buddha sculptures" }
    ],
    hospitals: ["Kampong Thom Provincial Hospital (062 961 345)"],
    restaurants: ["Stung Saen River Restaurant", "Arunras Restaurant Kampong Thom"],
    hotels: ["Glorious Hotel & Spa", "Sambor Village Hotel"],
    jobs: ["Cashew Nut & Rubber Processing", "Cultural Heritage Tourism"],
    housing: ["Stung Saen Riverside Residences", "National Road 6 Commercial Plots"],
    education: ["Chea Sim University of Kamchaymear Kampong Thom Campus"],
    transportation: ["National Road 6 Main Transit Corridor", "Express Inter-Provincial Vans"]
  },
  {
    id: "koh-kong",
    name: "Koh Kong",
    nameKh: "ខេត្តកោះកុង",
    capital: "Khemara Phoumin City",
    capitalKh: "ក្រុងខេមរភូមិន្ទ",
    tagline: "Eco-tourism frontier of the Cardamom Mountains, mangroves, and pristine coasts",
    taglineKh: "ឋានសួគ៌ទេសចរណ៍ធម្មជាតិ ជួរភ្នំក្រវ៉ាញ ព្រៃកោងកាងពាមក្រសោប និងកោះស្ដេច",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Peam Krasop Mangrove Sanctuary", nameKh: "តំបន់ការពារព្រៃកោងកាងពាមក្រសោប", desc: "Vast coastal mangrove boardwalks and suspension bridges" },
      { name: "Tatai River & Tatai Waterfall", nameKh: "ទឹកធ្លាក់តាតៃ & ដងព្រែកតាតៃ", desc: "Pristine emerald river flowing through the heart of the Cardamom rainforest" },
      { name: "Koh Sdach Archipelago", nameKh: "ប្រជុំកោះស្តេច", desc: "Crystal clear coral reefs and unspoiled island fishing villages" }
    ],
    hospitals: ["Koh Kong Provincial Referral Hospital (035 936 122)"],
    restaurants: ["Tatai River Floating Restaurant", "Koh Kong Bay Seafood Grills"],
    hotels: ["4 Rivers Floating Eco-Lodge (Tatai)", "Koh Kong Resort"],
    jobs: ["Cardamom Rainforest Conservation", "Deep-Sea Marine Fisheries", "Border Trade (Cham Yeam)"],
    housing: ["Khemara Phoumin Waterfront Homes", "Tatai Eco-Riverfront Plots"],
    education: ["Koh Kong Regional Vocational Training Center"],
    transportation: ["Koh Kong International Border (Thailand Link)", "National Road 48", "Coastal Speedboats"]
  },
  {
    id: "kratie",
    name: "Kratie",
    nameKh: "ខេត្តក្រចេះ",
    capital: "Kratie City",
    capitalKh: "ក្រុងក្រចេះ",
    tagline: "Sanctuary of rare freshwater Irrawaddy dolphins and quiet French colonial riverbanks",
    taglineKh: "ជម្រកសត្វផ្សោតក្បាលត្រឡោកទន្លេមេគង្គដ៏កម្រ និងផ្ទះបារាំងបុរាណមាត់ទន្លេ",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Kampi Irrawaddy Dolphin Conservation Pool", nameKh: "អន្លង់ផ្សោតកាំពី", desc: "Watch playful freshwater Irrawaddy dolphins swimming in Mekong waters" },
      { name: "Koh Trong Eco Island", nameKh: "កោះទ្រង់ (កោះទេសចរណ៍ធម្មជាតិ)", desc: "Peaceful car-free island famous for sweet pomelos, cycling, and homestays" },
      { name: "Phnom Sombok Hill Sanctuary", nameKh: "ភ្នំសំបុក", desc: "Lush meditation temple with views of the Mekong River valley" }
    ],
    hospitals: ["Kratie Provincial Hospital (072 971 430)"],
    restaurants: ["Le Tonle Training Restaurant", "Red Sun Falling River Bar", "Koh Trong Pomelo Stalls"],
    hotels: ["Soriyabori Resort (Koh Trong Island)", "River Dolphin Hotel Kratie"],
    jobs: ["Mekong Dolphin Conservation Eco-Tours", "Pomelo & Organic Agriculture"],
    housing: ["Kratie Riverside French-Style Houses", "Koh Trong Eco-Land Plots"],
    education: ["University of Kratie (UK)"],
    transportation: ["Koh Trong River Ferry", "Mekong Highway 73 & National Road 7"]
  },
  {
    id: "preah-vihear",
    name: "Preah Vihear",
    nameKh: "ខេត្តព្រះវិហារ",
    capital: "Tbeng Meanchey City",
    capitalKh: "ក្រុងត្បែងមានជ័យ",
    tagline: "Home to the spectacular cliff-top Temple of Preah Vihear UNESCO World Heritage",
    taglineKh: "ទឹកដីប្រាសាទព្រះវិហារលើកំពូលភ្នំដងរែក សម្បត្តិបេតិកភណ្ឌពិភពលោក UNESCO",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Preah Vihear Cliff Temple (UNESCO)", nameKh: "ប្រាសាទព្រះវិហារ (លើកំពូលភ្នំដងរែក ៥២៥ម)", desc: "11th-century mountain sanctuary crowning a dramatic 525m cliff" },
      { name: "Koh Ker Pyramid Temple Complex (UNESCO)", nameKh: "រមណីយដ្ឋានប្រាសាទកោះកេរ្តិ៍ (ប្រាសាទពីរ៉ាមីត ៧ជាន់)", desc: "10th-century capital with 7-tiered Prasat Thom step pyramid in forest" }
    ],
    hospitals: ["16 Makara Provincial Referral Hospital Preah Vihear (064 954 119)"],
    restaurants: ["Tbeng Meanchey Wild Honey & Food", "Preah Vihear Summit Panorama Cafe"],
    hotels: ["Preah Vihear Boutique Hotel", "Koh Ker Jungle Lodge"],
    jobs: ["UNESCO Archaeological Park Care", "Highland Agriculture & Cassava"],
    housing: ["Tbeng Meanchey New Urban Shophouses", "Sra Em Border Town Plots"],
    education: ["Preah Vihear Vocational Institute"],
    transportation: ["Mountain 4x4 Preah Vihear Shuttle", "National Road 62 Highway"]
  },
  {
    id: "pursat",
    name: "Pursat",
    nameKh: "ខេត្តពោធិ៍សាត់",
    capital: "Pursat City",
    capitalKh: "ក្រុងពោធិ៍សាត់",
    tagline: "Famous for marble stone carving, citrus oranges, and Kravanh mountain pass",
    taglineKh: "ទឹកដីចម្លាក់ថ្មម៉ាប ក្រូចពោធិ៍សាត់ផ្អែមឆ្ងាញ់ និងផ្លូវបុប្ផាលាក់ខ្លួនភ្នំ១៥០០",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Phnom 1500 (Route 55 Mountain Pass)", nameKh: "ភ្នំ១៥០០ (ផ្លូវបុប្ផាលាក់ខ្លួន ផ្លូវជាតិលេខ៥៥)", desc: "Breathtaking serpentine mountain road with clouds and jungle view" },
      { name: "Kompong Luong Tonle Sap Floating Town", nameKh: "ភូមិបណ្តែតទឹកកំពង់ហ្លួង", desc: "Massive floating city of 10,000 residents on the Tonle Sap lake" },
      { name: "Marble Stone Carving Villages", nameKh: "ភូមិចម្លាក់ថ្មភ្នំព្រះ (ថ្មកែវពោធិ៍សាត់)", desc: "Master artisans sculpting Buddha statues from native marble stone" }
    ],
    hospitals: ["Pursat Provincial Hospital (052 951 456)"],
    restaurants: ["Pursat Orange Orchard Dining", "Phnom 1500 Peak View Reststop"],
    hotels: ["KM Hotel Pursat", "Phnom 1500 Mountain Eco Resort"],
    jobs: ["Pursat Citrus (Oranges) Cultivation", "Marble Artistry", "Cardamom Eco-Guiding"],
    housing: ["Pursat Riverfront Townhouses", "Route 55 Mountain Land"],
    education: ["Pursat Regional Technical Training Center"],
    transportation: ["Royal Railway Northern Line (Pursat Station)", "National Road 55 to Thai Border"]
  },
  {
    id: "ratanakiri",
    name: "Ratanakiri",
    nameKh: "ខេត្តរតនគិរី",
    capital: "Banlung City",
    capitalKh: "ក្រុងបានលុង",
    tagline: "Volcanic lake Yeak Laom, gem mining, waterfalls, and rich indigenous culture",
    taglineKh: "ទឹកដីបឹងយក្សឡោមភ្នំភ្លើងបុរាណ ត្បូងកណ្តៀង ទឹកធ្លាក់កាចាញ និងវប្បធម៌ជនជាតិដើមភាគតិច",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Yeak Laom Volcanic Crater Lake", nameKh: "បឹងយក្សឡោម (បឹងភ្នំភ្លើងបុរាណ)", desc: "Pristine circular emerald volcanic crater lake surrounded by sacred rainforest" },
      { name: "Ka Chanh & Cha Ong Waterfalls", nameKh: "ទឹកធ្លាក់កាចាញ & ទឹកធ្លាក់ចាអ៊ុង", desc: "Spectacular jungle waterfalls with suspension bridge walking trails" },
      { name: "Lumphat Wildlife Sanctuary", nameKh: "ដែនជម្រកសត្វព្រៃលំផាត់", desc: "Vast protected savannah and forest home to giant ibises and wild cattle" }
    ],
    hospitals: ["Ratanakiri Provincial Referral Hospital (075 974 119)"],
    restaurants: ["Banlung Balcony Restaurant", "Cafe Yeak Laom", "Indigenous Bamboo-Cooked Rice Stalls"],
    hotels: ["Terres Rouges Lodge (Heritage Resort)", "Yeak Loam Hotel Banlung"],
    jobs: ["Precious Gemstone Trading (Zircons)", "Rubber, Coffee & Cashew Plantations", "Eco-Trek Guides"],
    housing: ["Banlung Lakeview Properties", "Volcanic Red-Soil Farmsteads"],
    education: ["Banlung Vocational Training Institute"],
    transportation: ["Ratanakiri Express Vans (Phnom Penh ⇄ Banlung)", "Banlung 4x4 Jungle Transport"]
  },
  {
    id: "stung-treng",
    name: "Stung Treng",
    nameKh: "ខេត្តស្ទឹងត្រែង",
    capital: "Stung Treng City",
    capitalKh: "ក្រុងស្ទឹងត្រែង",
    tagline: "Where the Mekong and Sekong rivers meet, rich in unique sweet fish and river Ramsar wetlands",
    taglineKh: "ចំណុចប្រសព្វទន្លេមេគង្គ និងទន្លេសេកុង សម្បូរត្រីប៉ាស៊ីអ៊ី និងតំបន់ដីសើមរ៉ាមសារ",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Mekong Ramsar Wetlands & Flooded Forests", nameKh: "តំបន់ដីសើមរ៉ាមសារទន្លេមេគង្គ", desc: "Ancient flooded trees standing in rapids creating mystical waterways" },
      { name: "Preah Nimith Waterfalls (Mekong Falls on Laos Border)", nameKh: "ទឹកធ្លាក់ព្រះនិមិត្ត (ព្រំដែនឡាវ)", desc: "Thunderous Mekong river falls where the mighty river enters Cambodia" }
    ],
    hospitals: ["Stung Treng Provincial Referral Hospital (074 973 119)"],
    restaurants: ["Sekong River View Restaurant", "Pa Si Ee Mekong Sweet Fish Stalls"],
    hotels: ["Mekong Bird Resort", "Golden River Hotel Stung Treng"],
    jobs: ["Mekong Fresh Fishery Operations", "Cross-Border Laos Commerce", "Eco-Tourism"],
    housing: ["Stung Treng Riverside Properties", "National Road 7 Commercial Land"],
    education: ["Stung Treng Regional Polytechnic College"],
    transportation: ["Stung Treng Mekong Bridge", "Laos International Border (Trapeang Kriel)"]
  },
  {
    id: "svay-rieng",
    name: "Svay Rieng",
    nameKh: "ខេត្តស្វាយរៀង",
    capital: "Svay Rieng City",
    capitalKh: "ក្រុងស្វាយរៀង",
    tagline: "Dynamic hub of Special Economic Zones and international trade with Vietnam at Bavet",
    taglineKh: "មជ្ឈមណ្ឌលតំបន់សេដ្ឋកិច្ចពិសេស និងច្រកទ្វារពាណិជ្ជកម្មអន្តរជាតិបាវិត-វៀតណាម",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Bavet International Border Gate", nameKh: "ច្រកទ្វារព្រំដែនអន្តរជាតិបាវិត", desc: "Thriving international trade, duty-free, and manufacturing zone" },
      { name: "Waiko River Park & Promenade", nameKh: "សួនមាត់ទន្លេវ៉ៃគោ ស្វាយរៀង", desc: "Beautiful evening riverside promenade with lotus ponds and walking paths" }
    ],
    hospitals: ["Svay Rieng Provincial Referral Hospital (044 945 744)", "Bavet International Clinic"],
    restaurants: ["Waiko Lotus View Restaurant", "Bavet International Dining"],
    hotels: ["Svay Rieng Riverside Hotel", "Titan King Casino & Hotel Bavet"],
    jobs: ["Manhattan & Tai Seng Special Economic Zones (SEZ)", "Logistics & Cross-Border Freight"],
    housing: ["Bavet SEZ Residential Shophouses", "Svay Rieng Downtown Townhomes"],
    education: ["Svay Rieng University (SRU)"],
    transportation: ["Phnom Penh - Bavet Expressway Route", "National Road 1 International Corridor"]
  },
  {
    id: "prey-veng",
    name: "Prey Veng",
    nameKh: "ខេត្តព្រៃវែង",
    capital: "Prey Veng City",
    capitalKh: "ក្រុងព្រៃវែង",
    tagline: "Heart of fertile delta plains, connected by the iconic Tsubasa Bridge (Neak Loeung)",
    taglineKh: "ទឹកដីវាលទំនាបកសិកម្មជីជាតិ និងស្ពានត្សឹបាសា (ស្ពានអ្នកលឿង) ដ៏ស្កឹមស្កៃ",
    image: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Tsubasa Bridge (Neak Loeung Bridge)", nameKh: "ស្ពានត្សឹបាសា (ស្ពានអ្នកលឿង)", desc: "Cambodia's longest cable-stayed bridge spanning 2.2km across the Mekong" },
      { name: "Ba Phnom Holy Mountain & Funan Heritage", nameKh: "រមណីយដ្ឋានប្រវត្តិសាស្ត្របាភ្នំ", desc: "Sacred hill associated with ancient Baphuon and Funan kingdom spirituality" }
    ],
    hospitals: ["Prey Veng Provincial Referral Hospital (043 944 322)", "Neak Loeung Referral Hospital"],
    restaurants: ["Neak Loeung Bridge River Grills", "Prey Veng Countryside Eateries"],
    hotels: ["Prey Veng River Hotel", "Neak Loeung Guesthouse"],
    jobs: ["Mekong Delta Intensive Rice Farming", "Aquaculture Fish Hatcheries"],
    housing: ["Prey Veng City Central Plots", "Neak Loeung Commercial Shophouses"],
    education: ["Chea Sim University of Kamchaymear (CSUK Main Campus)"],
    transportation: ["Tsubasa Bridge Highway", "National Road 1 & 11 Connecting Corridors"]
  },
  {
    id: "banteay-meanchey",
    name: "Banteay Meanchey",
    nameKh: "ខេត្តបន្ទាយមានជ័យ",
    capital: "Serei Saophoan City",
    capitalKh: "ក្រុងសិរីសោភ័ណ",
    tagline: "Border gateway at Poipet, home to monumental Banteay Chhmar stone temple",
    taglineKh: "ច្រកទ្វារពាណិជ្ជកម្មប៉ោយប៉ែត-ថៃ និងប្រាសាទបន្ទាយឆ្មារដ៏ធំស្កឹមស្កៃ",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Banteay Chhmar Temple Complex", nameKh: "ប្រាសាទបន្ទាយឆ្មារ", desc: "Immense 12th-century temple with famous multi-armed Lokeshvara bas-reliefs" },
      { name: "Poipet International Border & SEZ", nameKh: "ច្រកព្រំដែនអន្តរជាតិប៉ោយប៉ែត & តំបន់សេដ្ឋកិច្ចពិសេស", desc: "Bustling transit, manufacturing, and railway link to Thailand" }
    ],
    hospitals: ["Mongkol Borei Provincial Hospital (054 958 888)", "Poipet Referral Hospital"],
    restaurants: ["Serei Saophoan Garden Restaurant", "Poipet Border Street Market"],
    hotels: ["Poipet Grand Hotel", "Pyramid Luxury Hotel Serei Saophoan"],
    jobs: ["Poipet Special Economic Zone (SANCO SEZ)", "Cross-Border Trade with Thailand"],
    housing: ["Poipet Commercial Border Townhomes", "Serei Saophoan Subdivisions"],
    education: ["Meanchey University (MCU)"],
    transportation: ["Royal Railway Northern Line (Poipet Station)", "National Road 5 & 6 Junction"]
  },
  {
    id: "pailin",
    name: "Pailin",
    nameKh: "ខេត្តប៉ៃលិន",
    capital: "Pailin City",
    capitalKh: "ក្រុងប៉ៃលិន",
    tagline: "Gemstone highlands nestled in Cardamom foothills with authentic Kola cultural heritage",
    taglineKh: "ទឹកដីត្បូងទទឹម និងត្បូងកណ្តៀង វប្បធម៌កូឡា និងជើងភ្នំខៀវស្រស់ត្រកាល",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Phnom Yat Mountain Temple", nameKh: "វត្តភ្នំយ៉ាត (រឿងព្រេងត្បូងទទឹមប៉ៃលិន)", desc: "Sacred mountain pagoda featuring Kola culture statues and scenic city views" },
      { name: "Otavao Waterfall & Blue Mountain Stream", nameKh: "ទឹកធ្លាក់អូរតាវ៉ៅ", desc: "Refreshing natural waterfall cascading from the Cardamom peaks" }
    ],
    hospitals: ["Pailin Provincial Referral Hospital (053 953 119)"],
    restaurants: ["Pailin Kola Noodle Stalls", "Phnom Yat Mountain View Cafe"],
    hotels: ["Pailin Ruby Hotel", "Bamboo Resort Pailin"],
    jobs: ["Pailin Longan (Mien) Fruit Farming", "Gemstone Crafts", "Border Commerce (Psar Prum)"],
    housing: ["Pailin Foothill Orchard Land", "Downtown Pailin Shophouses"],
    education: ["Pailin Regional Training Center"],
    transportation: ["Psar Prum Border Crossing (To Chanthaburi, Thailand)", "National Road 57"]
  },
  {
    id: "oddar-meanchey",
    name: "Oddar Meanchey",
    nameKh: "ខេត្តឧត្តរមានជ័យ",
    capital: "Samraong City",
    capitalKh: "ក្រុងសំរោង",
    tagline: "Dangrek mountain passes, Choam international border, and historic Anlong Veng",
    taglineKh: "ខេត្តជើងភ្នំដងរែក ច្រកទ្វារអន្តរជាតិជាំ និងតំបន់ប្រវត្តិសាស្ត្រអន្លង់វែង",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Anlong Veng Historical Cliff & Peace Heritage", nameKh: "រមណីយដ្ឋានប្រវត្តិសាស្ត្រអន្លង់វែង", desc: "Historic sites of national reconciliation on the Dangrek mountain ridge" },
      { name: "Choam Border Pass & Dangrek Escarpment", nameKh: "ច្រកទ្វារអន្តរជាតិជាំ (ភ្នំដងរែក)", desc: "Dramatic mountain pass connecting Cambodia directly to northeast Thailand" }
    ],
    hospitals: ["Samraong Provincial Referral Hospital (065 962 119)"],
    restaurants: ["Samraong Lotus Lake Restaurant", "Choam Border Market Eateries"],
    hotels: ["Samraong City Hotel", "Anlong Veng Guesthouse"],
    jobs: ["Agri-Cashew & Cassava Export", "Cross-Border Commerce"],
    housing: ["Samraong Central Townhouses", "Anlong Veng Commercial Plots"],
    education: ["Oddar Meanchey Technical Institute"],
    transportation: ["National Road 67 & 68 Highways", "Choam International Border Gate"]
  },
  {
    id: "tboung-khmum",
    name: "Tboung Khmum",
    nameKh: "ខេត្តត្បូងឃ្មុំ",
    capital: "Suong City",
    capitalKh: "ក្រុងសួង",
    tagline: "Cambodia's newest province, famous for Chup rubber plantation and bustling trade at Memot",
    taglineKh: "ខេត្តកសិ-ឧស្សាហកម្មដ៏មានសក្តានុពល ចម្ការកៅស៊ូជប់ និងទីផ្សារពាណិជ្ជកម្មមេមត់",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
    attractions: [
      { name: "Chup Historical Rubber Plantation", nameKh: "ចម្ការកៅស៊ូជប់ (ធំជាងគេនៅកម្ពុជា)", desc: "Vast historic colonial-era rubber forests with towering canopy trees" },
      { name: "Memot Circular Earthworks (Prehistoric)", nameKh: "ភូមិបុរាណបន្ទាយគូ មេមត់", desc: "Mysterious circular earthwork settlements dating back 4,000 years" }
    ],
    hospitals: ["Tboung Khmum Provincial Hospital in Suong (042 942 119)", "Memot Referral Hospital"],
    restaurants: ["Suong City Garden Restaurant", "Chup Plantation Fresh Coffee"],
    hotels: ["Suong Center Hotel", "Tboung Khmum VIP Resort"],
    jobs: ["Commercial Rubber & Pepper Processing", "Agri-Business & Trade at Trapeang Phlong"],
    housing: ["Suong City New Development Zone", "Memot Border Commercial Lots"],
    education: ["Heng Samrin Thbong Khmum University (HSTKU)"],
    transportation: ["National Road 7 Highway", "Trapeang Phlong International Border to Vietnam"]
  }
];

// =========================================================================
// REAL VERIFIED JOBS IN CAMBODIA
// =========================================================================
export const realJobsList = [
  {
    id: "job-aba-frontend",
    title: "Senior Vue.js / Frontend Engineer",
    titleKh: "វិស្វករជាន់ខ្ពស់ Frontend (Vue.js)",
    company: "ABA Bank (Advanced Bank of Asia)",
    companyKh: "ធនាគារ អេប៊ីអេ (ABA Bank)",
    location: "Phnom Penh (Head Office, BKK1)",
    locationKh: "រាជធានីភ្នំពេញ (ការិយាល័យកណ្តាល បឹងកេងកង១)",
    salary: "$1,200 - $2,200 / month",
    type: "Full-time",
    typeKh: "ពេញម៉ោង",
    category: "it",
    postedAgo: "1 day ago",
    postedAgoKh: "១ ថ្ងៃមុន",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=500&auto=format&fit=crop&q=80",
    description: "Join ABA Bank's Digital Banking division building next-generation web platforms, merchant portals, and payment integrations serving millions of daily active users in Cambodia.",
    descriptionKh: "ចូលរួមជាមួយផ្នែកធនាគារឌីជីថលនៃធនាគារ ABA ក្នុងការអភិវឌ្ឍ Web Platform ទំនើប ប្រព័ន្ធទូទាត់ប្រាក់ និង Merchant Portal សម្រាប់អ្នកប្រើប្រាស់រាប់លាននាក់។",
    requirements: [
      "3+ years of professional experience with Vue.js 3, TypeScript, and modern CSS/Tailwind",
      "Solid understanding of REST APIs, WebSocket, and state management (Pinia/Vuex)",
      "Experience with secure financial / banking transactions and high availability",
      "Good communication skills in Khmer and English"
    ],
    requirementsKh: [
      "បទពិសោធន៍ ៣ឆ្នាំឡើងជាមួយ Vue.js 3, TypeScript និង Tailwind CSS",
      "យល់ដឹងច្បាស់ពី REST API, WebSocket និង Pinia",
      "មានបទពិសោធន៍ជាមួយប្រព័ន្ធហិរញ្ញវត្ថុ និងសុវត្ថិភាពខ្ពស់",
      "ចេះភាសាខ្មែរ និងអង់គ្លេសស្ទាត់ជំនាញ"
    ]
  },
  {
    id: "job-smart-marketing",
    title: "Digital Growth & Brand Marketing Lead",
    titleKh: "ប្រធានផ្នែកទីផ្សារឌីជីថល & Brand",
    company: "Smart Axiata Co., Ltd.",
    companyKh: "ក្រុមហ៊ុន ស្មាត អាស្យាតា (Smart Axiata)",
    location: "Phnom Penh (Monivong Blvd)",
    locationKh: "រាជធានីភ្នំពេញ (មហាវិថីព្រះមុនីវង្ស)",
    salary: "$900 - $1,500 / month",
    type: "Full-time",
    typeKh: "ពេញម៉ោង",
    category: "marketing",
    postedAgo: "2 days ago",
    postedAgoKh: "២ ថ្ងៃមុន",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=500&auto=format&fit=crop&q=80",
    description: "Lead digital engagement campaigns, music & gaming esports activations, and product launches for Smart's subscriber base across Cambodia.",
    descriptionKh: "ដឹកនាំយុទ្ធនាការទីផ្សារឌីជីថល ព្រឹត្តិការណ៍តន្ត្រី កីឡា eSports និងការដាក់ឱ្យប្រើប្រាស់សេវាកម្មថ្មីៗរបស់ Smart Axiata។",
    requirements: [
      "Bachelor's degree in Marketing, Communications, or Business Administration",
      "2-4 years experience managing omni-channel campaigns in Cambodia",
      "Proven track record in social media growth, influencer partnerships, and analytics",
      "Creative, self-driven, and collaborative team mindset"
    ],
    requirementsKh: [
      "បរិញ្ញាបត្រផ្នែកទីផ្សារ ទំនាក់ទំនង ឬគ្រប់គ្រងពាណិជ្ជកម្ម",
      "បទពិសោធន៍ ២ ទៅ ៤ ឆ្នាំក្នុងការគ្រប់គ្រងយុទ្ធនាការទីផ្សារ",
      "ជំនាញច្បាស់លាស់លើ Social Media Growth និង Influencer",
      "មានគំនិតច្នៃប្រឌិត និងភាពជាអ្នកដឹកនាំ"
    ]
  },
  {
    id: "job-chip-mong-retail",
    title: "Retail Operations & Customer Service Supervisor",
    titleKh: "ប្រធានត្រួតពិនិត្យប្រតិបត្តិការផ្សារទំនើប",
    company: "Chip Mong Retail (Chip Mong Group)",
    companyKh: "ក្រុមហ៊ុន ជីប ម៉ុង រីថែល (Chip Mong Group)",
    location: "Phnom Penh (Sen Sok / 271 Mega Mall)",
    locationKh: "រាជធានីភ្នំពេញ (ផ្សារទំនើប ជីប ម៉ុង មេហ្គាម៉ល)",
    salary: "$600 - $950 / month",
    type: "Full-time",
    typeKh: "ពេញម៉ោង",
    category: "sales",
    postedAgo: "3 days ago",
    postedAgoKh: "៣ ថ្ងៃមុន",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=500&auto=format&fit=crop&q=80",
    description: "Oversee daily store floor operations, merchandise inventory standards, customer experience quality, and staff scheduling at Chip Mong Supermarkets.",
    descriptionKh: "គ្រប់គ្រងប្រតិបត្តិការប្រចាំថ្ងៃក្នុងផ្សារទំនើប គ្រប់គ្រងស្តុកទំនិញ គុណភាពសេវាកម្មអតិថិជន និងរៀបចំកាលវិភាគបុគ្គលិក។",
    requirements: [
      "Degree in Business, Hospitality, or related field",
      "Minimum 2 years experience in retail, supermarket, or department store operations",
      "Strong leadership, problem-solving, and inventory management skills",
      "Good command of Khmer; English or Chinese is a plus"
    ],
    requirementsKh: [
      "សញ្ញាបត្រគ្រប់គ្រងពាណិជ្ជកម្ម ឬជំនាញពាក់ព័ន្ធ",
      "បទពិសោធន៍យ៉ាងតិច ២ឆ្នាំក្នុងផ្នែកផ្សារទំនើប ឬលក់រាយ",
      "មានភាពជាអ្នកដឹកនាំ និងដោះស្រាយបញ្ហាបានល្អ",
      "ចេះភាសាខ្មែរស្ទាត់ ចេះអង់គ្លេស ឬចិនកាន់តែប្រសើរ"
    ]
  }
];
